<?xml version="1.0" encoding="utf-8"?><Database Name="weixindb" Class="UserInfoDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.;Initial Catalog=weixindb;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="weixindbConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.WX_UserInfo" Member="WX_UserInfo">
    <Type Name="WX_UserInfo">
      <Column Name="OpenId" Type="System.String" DbType="NVarChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NickName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="HeadImgUrl" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Province" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Sex" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="RegistDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IsSubscibe" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>