/*
 * Copyright (C) 2015 - 2017 Microscene Inc., All Rights Reserved.
 *
 */
package com.vizen.sd.repository.mysql.mapper;

import com.vizen.framework.mybatis.BaseMapper;
import com.vizen.sd.repository.mysql.domain.Grid;
import com.vizen.sd.repository.mysql.domain.GridCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface GridMapper extends BaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grid
     */
    long countByExample(GridCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grid
     */
    int deleteByExample(GridCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grid
     */
    @Delete({
        "delete from grid",
        "where grid_id = #{gridId,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long gridId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grid
     */
    @Insert({
        "insert into grid (grid_id, grid_code, ",
        "parent_id, status, ",
        "is_valid, longitude_min, ",
        "longitude_max, latitude_min, ",
        "latitude_max)",
        "values (#{gridId,jdbcType=BIGINT}, #{gridCode,jdbcType=VARCHAR}, ",
        "#{parentId,jdbcType=BIGINT}, #{status,jdbcType=INTEGER}, ",
        "#{isValid,jdbcType=INTEGER}, #{longitudeMin,jdbcType=VARCHAR}, ",
        "#{longitudeMax,jdbcType=VARCHAR}, #{latitudeMin,jdbcType=VARCHAR}, ",
        "#{latitudeMax,jdbcType=VARCHAR})"
    })
    int insert(Grid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grid
     */
    int insertSelective(Grid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grid
     */
    List<Grid> selectByExample(GridCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grid
     */
    @Select({
        "select",
        "grid_id, grid_code, parent_id, status, is_valid, longitude_min, longitude_max, ",
        "latitude_min, latitude_max",
        "from grid",
        "where grid_id = #{gridId,jdbcType=BIGINT}"
    })
    @ResultMap("com.vizen.sd.repository.mysql.mapper.GridMapper.BaseResultMap")
    Grid selectByPrimaryKey(Long gridId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grid
     */
    int updateByExampleSelective(@Param("record") Grid record, @Param("example") GridCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grid
     */
    int updateByExample(@Param("record") Grid record, @Param("example") GridCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grid
     */
    int updateByPrimaryKeySelective(Grid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grid
     */
    @Update({
        "update grid",
        "set grid_code = #{gridCode,jdbcType=VARCHAR},",
          "parent_id = #{parentId,jdbcType=BIGINT},",
          "status = #{status,jdbcType=INTEGER},",
          "is_valid = #{isValid,jdbcType=INTEGER},",
          "longitude_min = #{longitudeMin,jdbcType=VARCHAR},",
          "longitude_max = #{longitudeMax,jdbcType=VARCHAR},",
          "latitude_min = #{latitudeMin,jdbcType=VARCHAR},",
          "latitude_max = #{latitudeMax,jdbcType=VARCHAR}",
        "where grid_id = #{gridId,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(Grid record);
}