/*
 * Copyright (C) 2015 - 2017 Microscene Inc., All Rights Reserved.
 *
 */
package com.vizen.sd.repository.mysql.mapper;

import com.vizen.framework.mybatis.BaseMapper;
import com.vizen.sd.repository.mysql.domain.GridPoiCriteria;
import com.vizen.sd.repository.mysql.domain.GridPoiKey;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;

public interface GridPoiMapper extends BaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grid_poi
     */
    long countByExample(GridPoiCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grid_poi
     */
    int deleteByExample(GridPoiCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grid_poi
     */
    @Delete({
        "delete from grid_poi",
        "where poi_id = #{poiId,jdbcType=VARCHAR}",
          "and grid_id = #{gridId,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(GridPoiKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grid_poi
     */
    @Insert({
        "insert into grid_poi (poi_id, grid_id)",
        "values (#{poiId,jdbcType=VARCHAR}, #{gridId,jdbcType=BIGINT})"
    })
    int insert(GridPoiKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grid_poi
     */
    int insertSelective(GridPoiKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grid_poi
     */
    List<GridPoiKey> selectByExample(GridPoiCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grid_poi
     */
    int updateByExampleSelective(@Param("record") GridPoiKey record, @Param("example") GridPoiCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grid_poi
     */
    int updateByExample(@Param("record") GridPoiKey record, @Param("example") GridPoiCriteria example);
}