/*
 * Copyright (C) 2015 - 2017 Microscene Inc., All Rights Reserved.
 *
 */
package com.vizen.sd.repository.mysql.mapper;

import com.vizen.framework.mybatis.BaseMapper;
import com.vizen.sd.repository.mysql.domain.PanoStitch;
import com.vizen.sd.repository.mysql.domain.PanoStitchCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface PanoStitchMapper extends BaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pano_stitch
     */
    long countByExample(PanoStitchCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pano_stitch
     */
    int deleteByExample(PanoStitchCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pano_stitch
     */
    @Delete({
        "delete from pano_stitch",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pano_stitch
     */
    @Insert({
        "insert into pano_stitch (id, name, ",
        "is_success, device_type, ",
        "stitch, creator_id, ",
        "create_time, updater_id, ",
        "update_time, begin_time, ",
        "waiting_time, finish_time, ",
        "is_valid)",
        "values (#{id,jdbcType=VARCHAR}, #{name,jdbcType=VARCHAR}, ",
        "#{isSuccess,jdbcType=INTEGER}, #{deviceType,jdbcType=INTEGER}, ",
        "#{stitch,jdbcType=VARCHAR}, #{creatorId,jdbcType=BIGINT}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{updaterId,jdbcType=BIGINT}, ",
        "#{updateTime,jdbcType=TIMESTAMP}, #{beginTime,jdbcType=TIMESTAMP}, ",
        "#{waitingTime,jdbcType=BIGINT}, #{finishTime,jdbcType=TIMESTAMP}, ",
        "#{isValid,jdbcType=INTEGER})"
    })
    int insert(PanoStitch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pano_stitch
     */
    int insertSelective(PanoStitch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pano_stitch
     */
    List<PanoStitch> selectByExample(PanoStitchCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pano_stitch
     */
    @Select({
        "select",
        "id, name, is_success, device_type, stitch, creator_id, create_time, updater_id, ",
        "update_time, begin_time, waiting_time, finish_time, is_valid",
        "from pano_stitch",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    @ResultMap("com.vizen.sd.repository.mysql.mapper.PanoStitchMapper.BaseResultMap")
    PanoStitch selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pano_stitch
     */
    int updateByExampleSelective(@Param("record") PanoStitch record, @Param("example") PanoStitchCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pano_stitch
     */
    int updateByExample(@Param("record") PanoStitch record, @Param("example") PanoStitchCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pano_stitch
     */
    int updateByPrimaryKeySelective(PanoStitch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pano_stitch
     */
    @Update({
        "update pano_stitch",
        "set name = #{name,jdbcType=VARCHAR},",
          "is_success = #{isSuccess,jdbcType=INTEGER},",
          "device_type = #{deviceType,jdbcType=INTEGER},",
          "stitch = #{stitch,jdbcType=VARCHAR},",
          "creator_id = #{creatorId,jdbcType=BIGINT},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "updater_id = #{updaterId,jdbcType=BIGINT},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP},",
          "begin_time = #{beginTime,jdbcType=TIMESTAMP},",
          "waiting_time = #{waitingTime,jdbcType=BIGINT},",
          "finish_time = #{finishTime,jdbcType=TIMESTAMP},",
          "is_valid = #{isValid,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(PanoStitch record);
}