/*
 * Copyright (C) 2015 - 2017 Microscene Inc., All Rights Reserved.
 *
 */
package com.vizen.sd.repository.mysql.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

import com.vizen.framework.mybatis.BaseMapper;
import com.vizen.sd.repository.mysql.domain.Resource;
import com.vizen.sd.repository.mysql.domain.ResourceCriteria;
import com.vizen.sd.repository.mysql.domain.UserPermission;

public interface ResourceMapper extends BaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     */
    long countByExample(ResourceCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     */
    int deleteByExample(ResourceCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     */
    @Delete({
        "delete from resource",
        "where resource_id = #{resourceId,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long resourceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     */
    @Insert({
        "insert into resource (resource_id, resource_name, ",
        "menu_id, uri_pattern, ",
        "status, create_time, ",
        "is_valid, method_type)",
        "values (#{resourceId,jdbcType=BIGINT}, #{resourceName,jdbcType=VARCHAR}, ",
        "#{menuId,jdbcType=BIGINT}, #{uriPattern,jdbcType=VARCHAR}, ",
        "#{status,jdbcType=INTEGER}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{isValid,jdbcType=TINYINT}, #{methodType,jdbcType=VARCHAR})"
    })
    int insert(Resource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     */
    int insertSelective(Resource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     */
    List<Resource> selectByExample(ResourceCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     */
    @Select({
        "select",
        "resource_id, resource_name, menu_id, uri_pattern, status, create_time, is_valid, ",
        "method_type",
        "from resource",
        "where resource_id = #{resourceId,jdbcType=BIGINT}"
    })
    @ResultMap("com.vizen.sd.repository.mysql.mapper.ResourceMapper.BaseResultMap")
    Resource selectByPrimaryKey(Long resourceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     */
    int updateByExampleSelective(@Param("record") Resource record, @Param("example") ResourceCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     */
    int updateByExample(@Param("record") Resource record, @Param("example") ResourceCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     */
    int updateByPrimaryKeySelective(Resource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     */
    @Update({
        "update resource",
        "set resource_name = #{resourceName,jdbcType=VARCHAR},",
          "menu_id = #{menuId,jdbcType=BIGINT},",
          "uri_pattern = #{uriPattern,jdbcType=VARCHAR},",
          "status = #{status,jdbcType=INTEGER},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "is_valid = #{isValid,jdbcType=TINYINT},",
          "method_type = #{methodType,jdbcType=VARCHAR}",
        "where resource_id = #{resourceId,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(Resource record);
    
    List<UserPermission> selectUserPermission(@Param("userName")String userName);
}