/*
 * Copyright (C) 2015 - 2017 Microscene Inc., All Rights Reserved.
 *
 */
package com.vizen.sd.repository.mysql.mapper;

import com.vizen.framework.mybatis.BaseMapper;
import com.vizen.sd.repository.mysql.domain.SysMenu;
import com.vizen.sd.repository.mysql.domain.SysMenuCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface SysMenuMapper extends BaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     */
    long countByExample(SysMenuCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     */
    int deleteByExample(SysMenuCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     */
    @Delete({
        "delete from sys_menu",
        "where menu_id = #{menuId,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long menuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     */
    @Insert({
        "insert into sys_menu (menu_id, menu_code, ",
        "menu_name, seq, create_time, ",
        "description, parent_id, ",
        "menu_status, is_valid)",
        "values (#{menuId,jdbcType=BIGINT}, #{menuCode,jdbcType=VARCHAR}, ",
        "#{menuName,jdbcType=VARCHAR}, #{seq,jdbcType=INTEGER}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{description,jdbcType=VARCHAR}, #{parentId,jdbcType=CHAR}, ",
        "#{menuStatus,jdbcType=TINYINT}, #{isValid,jdbcType=TINYINT})"
    })
    int insert(SysMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     */
    int insertSelective(SysMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     */
    List<SysMenu> selectByExample(SysMenuCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     */
    @Select({
        "select",
        "menu_id, menu_code, menu_name, seq, create_time, description, parent_id, menu_status, ",
        "is_valid",
        "from sys_menu",
        "where menu_id = #{menuId,jdbcType=BIGINT}"
    })
    @ResultMap("com.vizen.sd.repository.mysql.mapper.SysMenuMapper.BaseResultMap")
    SysMenu selectByPrimaryKey(Long menuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     */
    int updateByExampleSelective(@Param("record") SysMenu record, @Param("example") SysMenuCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     */
    int updateByExample(@Param("record") SysMenu record, @Param("example") SysMenuCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     */
    int updateByPrimaryKeySelective(SysMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     */
    @Update({
        "update sys_menu",
        "set menu_code = #{menuCode,jdbcType=VARCHAR},",
          "menu_name = #{menuName,jdbcType=VARCHAR},",
          "seq = #{seq,jdbcType=INTEGER},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "description = #{description,jdbcType=VARCHAR},",
          "parent_id = #{parentId,jdbcType=CHAR},",
          "menu_status = #{menuStatus,jdbcType=TINYINT},",
          "is_valid = #{isValid,jdbcType=TINYINT}",
        "where menu_id = #{menuId,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(SysMenu record);
}