/*
 * Copyright (C) 2015 - 2017 Microscene Inc., All Rights Reserved.
 *
 */
package com.vizen.sd.repository.mysql.mapper;

import com.vizen.framework.mybatis.BaseMapper;
import com.vizen.sd.repository.mysql.domain.Tag;
import com.vizen.sd.repository.mysql.domain.TagCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface TagMapper extends BaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag
     */
    long countByExample(TagCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag
     */
    int deleteByExample(TagCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag
     */
    @Delete({
        "delete from tag",
        "where tag_id = #{tagId,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long tagId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag
     */
    @Insert({
        "insert into tag (tag_id, tag_name, ",
        "is_valid)",
        "values (#{tagId,jdbcType=BIGINT}, #{tagName,jdbcType=VARCHAR}, ",
        "#{isValid,jdbcType=CHAR})"
    })
    int insert(Tag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag
     */
    int insertSelective(Tag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag
     */
    List<Tag> selectByExample(TagCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag
     */
    @Select({
        "select",
        "tag_id, tag_name, is_valid",
        "from tag",
        "where tag_id = #{tagId,jdbcType=BIGINT}"
    })
    @ResultMap("com.vizen.sd.repository.mysql.mapper.TagMapper.BaseResultMap")
    Tag selectByPrimaryKey(Long tagId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag
     */
    int updateByExampleSelective(@Param("record") Tag record, @Param("example") TagCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag
     */
    int updateByExample(@Param("record") Tag record, @Param("example") TagCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag
     */
    int updateByPrimaryKeySelective(Tag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag
     */
    @Update({
        "update tag",
        "set tag_name = #{tagName,jdbcType=VARCHAR},",
          "is_valid = #{isValid,jdbcType=CHAR}",
        "where tag_id = #{tagId,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(Tag record);
}