/*
 * Copyright (C) 2015 - 2017 Microscene Inc., All Rights Reserved.
 *
 */
package com.vizen.sd.repository.mysql.domain;

import com.vizen.framework.mybatis.BaseModel;
import java.io.Serializable;

/**
 *
 * @author mark@visualbusiness.com
 * @date 2017-12-26
 *
 */
public class GridPoiKey extends BaseModel implements Serializable {
    private String poiId;

    private Long gridId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table grid_poi
     */
    private static final long serialVersionUID = 1L;

    /**
     * @return poi_id
     */
    public String getPoiId() {
        return poiId;
    }

    /**
     * @param poiId
     */
    public void setPoiId(String poiId) {
        this.poiId = poiId == null ? null : poiId.trim();
    }

    /**
     * @return grid_id
     */
    public Long getGridId() {
        return gridId;
    }

    /**
     * @param gridId
     */
    public void setGridId(Long gridId) {
        this.gridId = gridId;
    }

    @Override
    public String toString() {
        return "GridPoiKey [poiId=" + poiId + ",gridId=" + gridId + "->" + super.toString() + "]";
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grid_poi
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        GridPoiKey other = (GridPoiKey) that;
        return (this.getPoiId() == null ? other.getPoiId() == null : this.getPoiId().equals(other.getPoiId()))
            && (this.getGridId() == null ? other.getGridId() == null : this.getGridId().equals(other.getGridId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grid_poi
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getPoiId() == null) ? 0 : getPoiId().hashCode());
        result = prime * result + ((getGridId() == null) ? 0 : getGridId().hashCode());
        return result;
    }
}