/*
 * Copyright (C) 2015 - 2017 Microscene Inc., All Rights Reserved.
 *
 */
package com.vizen.sd.repository.mysql.domain;

import java.util.ArrayList;
import java.util.List;

public class GridJumpCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table grid_jump
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table grid_jump
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table grid_jump
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grid_jump
     */
    public GridJumpCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grid_jump
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grid_jump
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grid_jump
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grid_jump
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grid_jump
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grid_jump
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grid_jump
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grid_jump
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grid_jump
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grid_jump
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    @Override
    public String toString() {
        return "GridJumpCriteria [orderByClause=" + orderByClause + ",distinct=" + distinct + ",oredCriteria=" + oredCriteria + "]";
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table grid_jump
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            if(value == null)return (Criteria)this;
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            if(value == null)return (Criteria)this;
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            if(value == null)return (Criteria)this;
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            if(value == null)return (Criteria)this;
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            if(value == null)return (Criteria)this;
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            if(value == null)return (Criteria)this;
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            if(values == null)return (Criteria)this;
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            if(values == null)return (Criteria)this;
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            if(value1 == null || value2 == null)return (Criteria)this;
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            if(value1 == null || value2 == null)return (Criteria)this;
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andJumpMarkIsNull() {
            addCriterion("jump_mark is null");
            return (Criteria) this;
        }

        public Criteria andJumpMarkIsNotNull() {
            addCriterion("jump_mark is not null");
            return (Criteria) this;
        }

        public Criteria andJumpMarkEqualTo(String value) {
            if(value == null)return (Criteria)this;
            addCriterion("jump_mark =", value, "jumpMark");
            return (Criteria) this;
        }

        public Criteria andJumpMarkNotEqualTo(String value) {
            if(value == null)return (Criteria)this;
            addCriterion("jump_mark <>", value, "jumpMark");
            return (Criteria) this;
        }

        public Criteria andJumpMarkGreaterThan(String value) {
            if(value == null)return (Criteria)this;
            addCriterion("jump_mark >", value, "jumpMark");
            return (Criteria) this;
        }

        public Criteria andJumpMarkGreaterThanOrEqualTo(String value) {
            if(value == null)return (Criteria)this;
            addCriterion("jump_mark >=", value, "jumpMark");
            return (Criteria) this;
        }

        public Criteria andJumpMarkLessThan(String value) {
            if(value == null)return (Criteria)this;
            addCriterion("jump_mark <", value, "jumpMark");
            return (Criteria) this;
        }

        public Criteria andJumpMarkLessThanOrEqualTo(String value) {
            if(value == null)return (Criteria)this;
            addCriterion("jump_mark <=", value, "jumpMark");
            return (Criteria) this;
        }

        public Criteria andJumpMarkLike(String value) {
            if(value == null)return (Criteria)this;
            addCriterion("jump_mark like", value, "jumpMark");
            return (Criteria) this;
        }

        public Criteria andJumpMarkNotLike(String value) {
            if(value == null)return (Criteria)this;
            addCriterion("jump_mark not like", value, "jumpMark");
            return (Criteria) this;
        }

        public Criteria andJumpMarkIn(List<String> values) {
            if(values == null)return (Criteria)this;
            addCriterion("jump_mark in", values, "jumpMark");
            return (Criteria) this;
        }

        public Criteria andJumpMarkNotIn(List<String> values) {
            if(values == null)return (Criteria)this;
            addCriterion("jump_mark not in", values, "jumpMark");
            return (Criteria) this;
        }

        public Criteria andJumpMarkBetween(String value1, String value2) {
            if(value1 == null || value2 == null)return (Criteria)this;
            addCriterion("jump_mark between", value1, value2, "jumpMark");
            return (Criteria) this;
        }

        public Criteria andJumpMarkNotBetween(String value1, String value2) {
            if(value1 == null || value2 == null)return (Criteria)this;
            addCriterion("jump_mark not between", value1, value2, "jumpMark");
            return (Criteria) this;
        }

        public Criteria andJumpGridIdIsNull() {
            addCriterion("jump_grid_id is null");
            return (Criteria) this;
        }

        public Criteria andJumpGridIdIsNotNull() {
            addCriterion("jump_grid_id is not null");
            return (Criteria) this;
        }

        public Criteria andJumpGridIdEqualTo(Long value) {
            if(value == null)return (Criteria)this;
            addCriterion("jump_grid_id =", value, "jumpGridId");
            return (Criteria) this;
        }

        public Criteria andJumpGridIdNotEqualTo(Long value) {
            if(value == null)return (Criteria)this;
            addCriterion("jump_grid_id <>", value, "jumpGridId");
            return (Criteria) this;
        }

        public Criteria andJumpGridIdGreaterThan(Long value) {
            if(value == null)return (Criteria)this;
            addCriterion("jump_grid_id >", value, "jumpGridId");
            return (Criteria) this;
        }

        public Criteria andJumpGridIdGreaterThanOrEqualTo(Long value) {
            if(value == null)return (Criteria)this;
            addCriterion("jump_grid_id >=", value, "jumpGridId");
            return (Criteria) this;
        }

        public Criteria andJumpGridIdLessThan(Long value) {
            if(value == null)return (Criteria)this;
            addCriterion("jump_grid_id <", value, "jumpGridId");
            return (Criteria) this;
        }

        public Criteria andJumpGridIdLessThanOrEqualTo(Long value) {
            if(value == null)return (Criteria)this;
            addCriterion("jump_grid_id <=", value, "jumpGridId");
            return (Criteria) this;
        }

        public Criteria andJumpGridIdIn(List<Long> values) {
            if(values == null)return (Criteria)this;
            addCriterion("jump_grid_id in", values, "jumpGridId");
            return (Criteria) this;
        }

        public Criteria andJumpGridIdNotIn(List<Long> values) {
            if(values == null)return (Criteria)this;
            addCriterion("jump_grid_id not in", values, "jumpGridId");
            return (Criteria) this;
        }

        public Criteria andJumpGridIdBetween(Long value1, Long value2) {
            if(value1 == null || value2 == null)return (Criteria)this;
            addCriterion("jump_grid_id between", value1, value2, "jumpGridId");
            return (Criteria) this;
        }

        public Criteria andJumpGridIdNotBetween(Long value1, Long value2) {
            if(value1 == null || value2 == null)return (Criteria)this;
            addCriterion("jump_grid_id not between", value1, value2, "jumpGridId");
            return (Criteria) this;
        }

        public Criteria andJumpGridCodeIsNull() {
            addCriterion("jump_grid_code is null");
            return (Criteria) this;
        }

        public Criteria andJumpGridCodeIsNotNull() {
            addCriterion("jump_grid_code is not null");
            return (Criteria) this;
        }

        public Criteria andJumpGridCodeEqualTo(String value) {
            if(value == null)return (Criteria)this;
            addCriterion("jump_grid_code =", value, "jumpGridCode");
            return (Criteria) this;
        }

        public Criteria andJumpGridCodeNotEqualTo(String value) {
            if(value == null)return (Criteria)this;
            addCriterion("jump_grid_code <>", value, "jumpGridCode");
            return (Criteria) this;
        }

        public Criteria andJumpGridCodeGreaterThan(String value) {
            if(value == null)return (Criteria)this;
            addCriterion("jump_grid_code >", value, "jumpGridCode");
            return (Criteria) this;
        }

        public Criteria andJumpGridCodeGreaterThanOrEqualTo(String value) {
            if(value == null)return (Criteria)this;
            addCriterion("jump_grid_code >=", value, "jumpGridCode");
            return (Criteria) this;
        }

        public Criteria andJumpGridCodeLessThan(String value) {
            if(value == null)return (Criteria)this;
            addCriterion("jump_grid_code <", value, "jumpGridCode");
            return (Criteria) this;
        }

        public Criteria andJumpGridCodeLessThanOrEqualTo(String value) {
            if(value == null)return (Criteria)this;
            addCriterion("jump_grid_code <=", value, "jumpGridCode");
            return (Criteria) this;
        }

        public Criteria andJumpGridCodeLike(String value) {
            if(value == null)return (Criteria)this;
            addCriterion("jump_grid_code like", value, "jumpGridCode");
            return (Criteria) this;
        }

        public Criteria andJumpGridCodeNotLike(String value) {
            if(value == null)return (Criteria)this;
            addCriterion("jump_grid_code not like", value, "jumpGridCode");
            return (Criteria) this;
        }

        public Criteria andJumpGridCodeIn(List<String> values) {
            if(values == null)return (Criteria)this;
            addCriterion("jump_grid_code in", values, "jumpGridCode");
            return (Criteria) this;
        }

        public Criteria andJumpGridCodeNotIn(List<String> values) {
            if(values == null)return (Criteria)this;
            addCriterion("jump_grid_code not in", values, "jumpGridCode");
            return (Criteria) this;
        }

        public Criteria andJumpGridCodeBetween(String value1, String value2) {
            if(value1 == null || value2 == null)return (Criteria)this;
            addCriterion("jump_grid_code between", value1, value2, "jumpGridCode");
            return (Criteria) this;
        }

        public Criteria andJumpGridCodeNotBetween(String value1, String value2) {
            if(value1 == null || value2 == null)return (Criteria)this;
            addCriterion("jump_grid_code not between", value1, value2, "jumpGridCode");
            return (Criteria) this;
        }

        public Criteria andJumpPanoIdIsNull() {
            addCriterion("jump_pano_id is null");
            return (Criteria) this;
        }

        public Criteria andJumpPanoIdIsNotNull() {
            addCriterion("jump_pano_id is not null");
            return (Criteria) this;
        }

        public Criteria andJumpPanoIdEqualTo(String value) {
            if(value == null)return (Criteria)this;
            addCriterion("jump_pano_id =", value, "jumpPanoId");
            return (Criteria) this;
        }

        public Criteria andJumpPanoIdNotEqualTo(String value) {
            if(value == null)return (Criteria)this;
            addCriterion("jump_pano_id <>", value, "jumpPanoId");
            return (Criteria) this;
        }

        public Criteria andJumpPanoIdGreaterThan(String value) {
            if(value == null)return (Criteria)this;
            addCriterion("jump_pano_id >", value, "jumpPanoId");
            return (Criteria) this;
        }

        public Criteria andJumpPanoIdGreaterThanOrEqualTo(String value) {
            if(value == null)return (Criteria)this;
            addCriterion("jump_pano_id >=", value, "jumpPanoId");
            return (Criteria) this;
        }

        public Criteria andJumpPanoIdLessThan(String value) {
            if(value == null)return (Criteria)this;
            addCriterion("jump_pano_id <", value, "jumpPanoId");
            return (Criteria) this;
        }

        public Criteria andJumpPanoIdLessThanOrEqualTo(String value) {
            if(value == null)return (Criteria)this;
            addCriterion("jump_pano_id <=", value, "jumpPanoId");
            return (Criteria) this;
        }

        public Criteria andJumpPanoIdLike(String value) {
            if(value == null)return (Criteria)this;
            addCriterion("jump_pano_id like", value, "jumpPanoId");
            return (Criteria) this;
        }

        public Criteria andJumpPanoIdNotLike(String value) {
            if(value == null)return (Criteria)this;
            addCriterion("jump_pano_id not like", value, "jumpPanoId");
            return (Criteria) this;
        }

        public Criteria andJumpPanoIdIn(List<String> values) {
            if(values == null)return (Criteria)this;
            addCriterion("jump_pano_id in", values, "jumpPanoId");
            return (Criteria) this;
        }

        public Criteria andJumpPanoIdNotIn(List<String> values) {
            if(values == null)return (Criteria)this;
            addCriterion("jump_pano_id not in", values, "jumpPanoId");
            return (Criteria) this;
        }

        public Criteria andJumpPanoIdBetween(String value1, String value2) {
            if(value1 == null || value2 == null)return (Criteria)this;
            addCriterion("jump_pano_id between", value1, value2, "jumpPanoId");
            return (Criteria) this;
        }

        public Criteria andJumpPanoIdNotBetween(String value1, String value2) {
            if(value1 == null || value2 == null)return (Criteria)this;
            addCriterion("jump_pano_id not between", value1, value2, "jumpPanoId");
            return (Criteria) this;
        }

        public Criteria andJumpPanoNameIsNull() {
            addCriterion("jump_pano_name is null");
            return (Criteria) this;
        }

        public Criteria andJumpPanoNameIsNotNull() {
            addCriterion("jump_pano_name is not null");
            return (Criteria) this;
        }

        public Criteria andJumpPanoNameEqualTo(String value) {
            if(value == null)return (Criteria)this;
            addCriterion("jump_pano_name =", value, "jumpPanoName");
            return (Criteria) this;
        }

        public Criteria andJumpPanoNameNotEqualTo(String value) {
            if(value == null)return (Criteria)this;
            addCriterion("jump_pano_name <>", value, "jumpPanoName");
            return (Criteria) this;
        }

        public Criteria andJumpPanoNameGreaterThan(String value) {
            if(value == null)return (Criteria)this;
            addCriterion("jump_pano_name >", value, "jumpPanoName");
            return (Criteria) this;
        }

        public Criteria andJumpPanoNameGreaterThanOrEqualTo(String value) {
            if(value == null)return (Criteria)this;
            addCriterion("jump_pano_name >=", value, "jumpPanoName");
            return (Criteria) this;
        }

        public Criteria andJumpPanoNameLessThan(String value) {
            if(value == null)return (Criteria)this;
            addCriterion("jump_pano_name <", value, "jumpPanoName");
            return (Criteria) this;
        }

        public Criteria andJumpPanoNameLessThanOrEqualTo(String value) {
            if(value == null)return (Criteria)this;
            addCriterion("jump_pano_name <=", value, "jumpPanoName");
            return (Criteria) this;
        }

        public Criteria andJumpPanoNameLike(String value) {
            if(value == null)return (Criteria)this;
            addCriterion("jump_pano_name like", value, "jumpPanoName");
            return (Criteria) this;
        }

        public Criteria andJumpPanoNameNotLike(String value) {
            if(value == null)return (Criteria)this;
            addCriterion("jump_pano_name not like", value, "jumpPanoName");
            return (Criteria) this;
        }

        public Criteria andJumpPanoNameIn(List<String> values) {
            if(values == null)return (Criteria)this;
            addCriterion("jump_pano_name in", values, "jumpPanoName");
            return (Criteria) this;
        }

        public Criteria andJumpPanoNameNotIn(List<String> values) {
            if(values == null)return (Criteria)this;
            addCriterion("jump_pano_name not in", values, "jumpPanoName");
            return (Criteria) this;
        }

        public Criteria andJumpPanoNameBetween(String value1, String value2) {
            if(value1 == null || value2 == null)return (Criteria)this;
            addCriterion("jump_pano_name between", value1, value2, "jumpPanoName");
            return (Criteria) this;
        }

        public Criteria andJumpPanoNameNotBetween(String value1, String value2) {
            if(value1 == null || value2 == null)return (Criteria)this;
            addCriterion("jump_pano_name not between", value1, value2, "jumpPanoName");
            return (Criteria) this;
        }

        public Criteria andPositionIsNull() {
            addCriterion("position is null");
            return (Criteria) this;
        }

        public Criteria andPositionIsNotNull() {
            addCriterion("position is not null");
            return (Criteria) this;
        }

        public Criteria andPositionEqualTo(String value) {
            if(value == null)return (Criteria)this;
            addCriterion("position =", value, "position");
            return (Criteria) this;
        }

        public Criteria andPositionNotEqualTo(String value) {
            if(value == null)return (Criteria)this;
            addCriterion("position <>", value, "position");
            return (Criteria) this;
        }

        public Criteria andPositionGreaterThan(String value) {
            if(value == null)return (Criteria)this;
            addCriterion("position >", value, "position");
            return (Criteria) this;
        }

        public Criteria andPositionGreaterThanOrEqualTo(String value) {
            if(value == null)return (Criteria)this;
            addCriterion("position >=", value, "position");
            return (Criteria) this;
        }

        public Criteria andPositionLessThan(String value) {
            if(value == null)return (Criteria)this;
            addCriterion("position <", value, "position");
            return (Criteria) this;
        }

        public Criteria andPositionLessThanOrEqualTo(String value) {
            if(value == null)return (Criteria)this;
            addCriterion("position <=", value, "position");
            return (Criteria) this;
        }

        public Criteria andPositionLike(String value) {
            if(value == null)return (Criteria)this;
            addCriterion("position like", value, "position");
            return (Criteria) this;
        }

        public Criteria andPositionNotLike(String value) {
            if(value == null)return (Criteria)this;
            addCriterion("position not like", value, "position");
            return (Criteria) this;
        }

        public Criteria andPositionIn(List<String> values) {
            if(values == null)return (Criteria)this;
            addCriterion("position in", values, "position");
            return (Criteria) this;
        }

        public Criteria andPositionNotIn(List<String> values) {
            if(values == null)return (Criteria)this;
            addCriterion("position not in", values, "position");
            return (Criteria) this;
        }

        public Criteria andPositionBetween(String value1, String value2) {
            if(value1 == null || value2 == null)return (Criteria)this;
            addCriterion("position between", value1, value2, "position");
            return (Criteria) this;
        }

        public Criteria andPositionNotBetween(String value1, String value2) {
            if(value1 == null || value2 == null)return (Criteria)this;
            addCriterion("position not between", value1, value2, "position");
            return (Criteria) this;
        }

        public Criteria andGridIdIsNull() {
            addCriterion("grid_id is null");
            return (Criteria) this;
        }

        public Criteria andGridIdIsNotNull() {
            addCriterion("grid_id is not null");
            return (Criteria) this;
        }

        public Criteria andGridIdEqualTo(Long value) {
            if(value == null)return (Criteria)this;
            addCriterion("grid_id =", value, "gridId");
            return (Criteria) this;
        }

        public Criteria andGridIdNotEqualTo(Long value) {
            if(value == null)return (Criteria)this;
            addCriterion("grid_id <>", value, "gridId");
            return (Criteria) this;
        }

        public Criteria andGridIdGreaterThan(Long value) {
            if(value == null)return (Criteria)this;
            addCriterion("grid_id >", value, "gridId");
            return (Criteria) this;
        }

        public Criteria andGridIdGreaterThanOrEqualTo(Long value) {
            if(value == null)return (Criteria)this;
            addCriterion("grid_id >=", value, "gridId");
            return (Criteria) this;
        }

        public Criteria andGridIdLessThan(Long value) {
            if(value == null)return (Criteria)this;
            addCriterion("grid_id <", value, "gridId");
            return (Criteria) this;
        }

        public Criteria andGridIdLessThanOrEqualTo(Long value) {
            if(value == null)return (Criteria)this;
            addCriterion("grid_id <=", value, "gridId");
            return (Criteria) this;
        }

        public Criteria andGridIdIn(List<Long> values) {
            if(values == null)return (Criteria)this;
            addCriterion("grid_id in", values, "gridId");
            return (Criteria) this;
        }

        public Criteria andGridIdNotIn(List<Long> values) {
            if(values == null)return (Criteria)this;
            addCriterion("grid_id not in", values, "gridId");
            return (Criteria) this;
        }

        public Criteria andGridIdBetween(Long value1, Long value2) {
            if(value1 == null || value2 == null)return (Criteria)this;
            addCriterion("grid_id between", value1, value2, "gridId");
            return (Criteria) this;
        }

        public Criteria andGridIdNotBetween(Long value1, Long value2) {
            if(value1 == null || value2 == null)return (Criteria)this;
            addCriterion("grid_id not between", value1, value2, "gridId");
            return (Criteria) this;
        }

        public Criteria andGridCodeIsNull() {
            addCriterion("grid_code is null");
            return (Criteria) this;
        }

        public Criteria andGridCodeIsNotNull() {
            addCriterion("grid_code is not null");
            return (Criteria) this;
        }

        public Criteria andGridCodeEqualTo(String value) {
            if(value == null)return (Criteria)this;
            addCriterion("grid_code =", value, "gridCode");
            return (Criteria) this;
        }

        public Criteria andGridCodeNotEqualTo(String value) {
            if(value == null)return (Criteria)this;
            addCriterion("grid_code <>", value, "gridCode");
            return (Criteria) this;
        }

        public Criteria andGridCodeGreaterThan(String value) {
            if(value == null)return (Criteria)this;
            addCriterion("grid_code >", value, "gridCode");
            return (Criteria) this;
        }

        public Criteria andGridCodeGreaterThanOrEqualTo(String value) {
            if(value == null)return (Criteria)this;
            addCriterion("grid_code >=", value, "gridCode");
            return (Criteria) this;
        }

        public Criteria andGridCodeLessThan(String value) {
            if(value == null)return (Criteria)this;
            addCriterion("grid_code <", value, "gridCode");
            return (Criteria) this;
        }

        public Criteria andGridCodeLessThanOrEqualTo(String value) {
            if(value == null)return (Criteria)this;
            addCriterion("grid_code <=", value, "gridCode");
            return (Criteria) this;
        }

        public Criteria andGridCodeLike(String value) {
            if(value == null)return (Criteria)this;
            addCriterion("grid_code like", value, "gridCode");
            return (Criteria) this;
        }

        public Criteria andGridCodeNotLike(String value) {
            if(value == null)return (Criteria)this;
            addCriterion("grid_code not like", value, "gridCode");
            return (Criteria) this;
        }

        public Criteria andGridCodeIn(List<String> values) {
            if(values == null)return (Criteria)this;
            addCriterion("grid_code in", values, "gridCode");
            return (Criteria) this;
        }

        public Criteria andGridCodeNotIn(List<String> values) {
            if(values == null)return (Criteria)this;
            addCriterion("grid_code not in", values, "gridCode");
            return (Criteria) this;
        }

        public Criteria andGridCodeBetween(String value1, String value2) {
            if(value1 == null || value2 == null)return (Criteria)this;
            addCriterion("grid_code between", value1, value2, "gridCode");
            return (Criteria) this;
        }

        public Criteria andGridCodeNotBetween(String value1, String value2) {
            if(value1 == null || value2 == null)return (Criteria)this;
            addCriterion("grid_code not between", value1, value2, "gridCode");
            return (Criteria) this;
        }

        public Criteria andProjcetIdIsNull() {
            addCriterion("projcet_id is null");
            return (Criteria) this;
        }

        public Criteria andProjcetIdIsNotNull() {
            addCriterion("projcet_id is not null");
            return (Criteria) this;
        }

        public Criteria andProjcetIdEqualTo(Long value) {
            if(value == null)return (Criteria)this;
            addCriterion("projcet_id =", value, "projcetId");
            return (Criteria) this;
        }

        public Criteria andProjcetIdNotEqualTo(Long value) {
            if(value == null)return (Criteria)this;
            addCriterion("projcet_id <>", value, "projcetId");
            return (Criteria) this;
        }

        public Criteria andProjcetIdGreaterThan(Long value) {
            if(value == null)return (Criteria)this;
            addCriterion("projcet_id >", value, "projcetId");
            return (Criteria) this;
        }

        public Criteria andProjcetIdGreaterThanOrEqualTo(Long value) {
            if(value == null)return (Criteria)this;
            addCriterion("projcet_id >=", value, "projcetId");
            return (Criteria) this;
        }

        public Criteria andProjcetIdLessThan(Long value) {
            if(value == null)return (Criteria)this;
            addCriterion("projcet_id <", value, "projcetId");
            return (Criteria) this;
        }

        public Criteria andProjcetIdLessThanOrEqualTo(Long value) {
            if(value == null)return (Criteria)this;
            addCriterion("projcet_id <=", value, "projcetId");
            return (Criteria) this;
        }

        public Criteria andProjcetIdIn(List<Long> values) {
            if(values == null)return (Criteria)this;
            addCriterion("projcet_id in", values, "projcetId");
            return (Criteria) this;
        }

        public Criteria andProjcetIdNotIn(List<Long> values) {
            if(values == null)return (Criteria)this;
            addCriterion("projcet_id not in", values, "projcetId");
            return (Criteria) this;
        }

        public Criteria andProjcetIdBetween(Long value1, Long value2) {
            if(value1 == null || value2 == null)return (Criteria)this;
            addCriterion("projcet_id between", value1, value2, "projcetId");
            return (Criteria) this;
        }

        public Criteria andProjcetIdNotBetween(Long value1, Long value2) {
            if(value1 == null || value2 == null)return (Criteria)this;
            addCriterion("projcet_id not between", value1, value2, "projcetId");
            return (Criteria) this;
        }

        @Override
        public String toString() {
            return "GeneratedCriteria [criteria=" + criteria + "]";
        }

        public Criteria andJumpMarkLikeInsensitive(String value) {
            addCriterion("upper(jump_mark) like", value.toUpperCase(), "jumpMark");
            return (Criteria) this;
        }

        public Criteria andJumpGridCodeLikeInsensitive(String value) {
            addCriterion("upper(jump_grid_code) like", value.toUpperCase(), "jumpGridCode");
            return (Criteria) this;
        }

        public Criteria andJumpPanoIdLikeInsensitive(String value) {
            addCriterion("upper(jump_pano_id) like", value.toUpperCase(), "jumpPanoId");
            return (Criteria) this;
        }

        public Criteria andJumpPanoNameLikeInsensitive(String value) {
            addCriterion("upper(jump_pano_name) like", value.toUpperCase(), "jumpPanoName");
            return (Criteria) this;
        }

        public Criteria andPositionLikeInsensitive(String value) {
            addCriterion("upper(position) like", value.toUpperCase(), "position");
            return (Criteria) this;
        }

        public Criteria andGridCodeLikeInsensitive(String value) {
            addCriterion("upper(grid_code) like", value.toUpperCase(), "gridCode");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table grid_jump
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }

        @Override
        public String toString() {
            return "Criteria [->" + super.toString() + "]";
        }

        public Criteria setRowNum(String rowNum) {
            if(rowNum == null)return (Criteria)this;
            try {
                addCriterion("ROWNUM <=" + (Integer.parseInt(rowNum) + 1));
            } catch (NumberFormatException nfe) {
                throw new RuntimeException(nfe);
            }
            return this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table grid_jump
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }

        @Override
        public String toString() {
            return "Criterion [condition=" + condition + ",value=" + value + ",secondValue=" + secondValue + ",noValue=" + noValue + ",singleValue=" + singleValue + ",betweenValue=" + betweenValue + ",listValue=" + listValue + ",typeHandler=" + typeHandler + "]";
        }
    }
}