/*
 * Copyright (C) 2015 - 2017 Microscene Inc., All Rights Reserved.
 *
 */
package com.vizen.sd.repository.mysql.domain;

import com.vizen.framework.mybatis.BaseModel;
import java.io.Serializable;

/**
 *
 * @author mark@visualbusiness.com
 * @date 2017-12-20
 *
 */
public class Grid extends BaseModel implements Serializable {
    private Long gridId;

    /**
     * 网格代码
     */
    private String gridCode;

    private Long parentId;

    private Integer status;

    private Integer isValid;

    /**
     * 经度小
     */
    private String longitudeMin;

    /**
     * 经度大
     */
    private String longitudeMax;

    /**
     * 纬度小
     */
    private String latitudeMin;

    /**
     * 纬度大
     */
    private String latitudeMax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table grid
     */
    private static final long serialVersionUID = 1L;

    /**
     * @return grid_id
     */
    public Long getGridId() {
        return gridId;
    }

    /**
     * @param gridId
     */
    public void setGridId(Long gridId) {
        this.gridId = gridId;
    }

    /**
     * 获取网格代码
     *
     * @return grid_code - 网格代码
     */
    public String getGridCode() {
        return gridCode;
    }

    /**
     * 设置网格代码
     *
     * @param gridCode 网格代码
     */
    public void setGridCode(String gridCode) {
        this.gridCode = gridCode == null ? null : gridCode.trim();
    }

    /**
     * @return parent_id
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * @param parentId
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * @return status
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * @param status
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * @return is_valid
     */
    public Integer getIsValid() {
        return isValid;
    }

    /**
     * @param isValid
     */
    public void setIsValid(Integer isValid) {
        this.isValid = isValid;
    }

    /**
     * 获取经度小
     *
     * @return longitude_min - 经度小
     */
    public String getLongitudeMin() {
        return longitudeMin;
    }

    /**
     * 设置经度小
     *
     * @param longitudeMin 经度小
     */
    public void setLongitudeMin(String longitudeMin) {
        this.longitudeMin = longitudeMin == null ? null : longitudeMin.trim();
    }

    /**
     * 获取经度大
     *
     * @return longitude_max - 经度大
     */
    public String getLongitudeMax() {
        return longitudeMax;
    }

    /**
     * 设置经度大
     *
     * @param longitudeMax 经度大
     */
    public void setLongitudeMax(String longitudeMax) {
        this.longitudeMax = longitudeMax == null ? null : longitudeMax.trim();
    }

    /**
     * 获取纬度小
     *
     * @return latitude_min - 纬度小
     */
    public String getLatitudeMin() {
        return latitudeMin;
    }

    /**
     * 设置纬度小
     *
     * @param latitudeMin 纬度小
     */
    public void setLatitudeMin(String latitudeMin) {
        this.latitudeMin = latitudeMin == null ? null : latitudeMin.trim();
    }

    /**
     * 获取纬度大
     *
     * @return latitude_max - 纬度大
     */
    public String getLatitudeMax() {
        return latitudeMax;
    }

    /**
     * 设置纬度大
     *
     * @param latitudeMax 纬度大
     */
    public void setLatitudeMax(String latitudeMax) {
        this.latitudeMax = latitudeMax == null ? null : latitudeMax.trim();
    }

    @Override
    public String toString() {
        return "Grid [gridId=" + gridId + ",gridCode=" + gridCode + ",parentId=" + parentId + ",status=" + status + ",isValid=" + isValid + ",longitudeMin=" + longitudeMin + ",longitudeMax=" + longitudeMax + ",latitudeMin=" + latitudeMin + ",latitudeMax=" + latitudeMax + "->" + super.toString() + "]";
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grid
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Grid other = (Grid) that;
        return (this.getGridId() == null ? other.getGridId() == null : this.getGridId().equals(other.getGridId()))
            && (this.getGridCode() == null ? other.getGridCode() == null : this.getGridCode().equals(other.getGridCode()))
            && (this.getParentId() == null ? other.getParentId() == null : this.getParentId().equals(other.getParentId()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getIsValid() == null ? other.getIsValid() == null : this.getIsValid().equals(other.getIsValid()))
            && (this.getLongitudeMin() == null ? other.getLongitudeMin() == null : this.getLongitudeMin().equals(other.getLongitudeMin()))
            && (this.getLongitudeMax() == null ? other.getLongitudeMax() == null : this.getLongitudeMax().equals(other.getLongitudeMax()))
            && (this.getLatitudeMin() == null ? other.getLatitudeMin() == null : this.getLatitudeMin().equals(other.getLatitudeMin()))
            && (this.getLatitudeMax() == null ? other.getLatitudeMax() == null : this.getLatitudeMax().equals(other.getLatitudeMax()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grid
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getGridId() == null) ? 0 : getGridId().hashCode());
        result = prime * result + ((getGridCode() == null) ? 0 : getGridCode().hashCode());
        result = prime * result + ((getParentId() == null) ? 0 : getParentId().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getIsValid() == null) ? 0 : getIsValid().hashCode());
        result = prime * result + ((getLongitudeMin() == null) ? 0 : getLongitudeMin().hashCode());
        result = prime * result + ((getLongitudeMax() == null) ? 0 : getLongitudeMax().hashCode());
        result = prime * result + ((getLatitudeMin() == null) ? 0 : getLatitudeMin().hashCode());
        result = prime * result + ((getLatitudeMax() == null) ? 0 : getLatitudeMax().hashCode());
        return result;
    }
}