/*
 * Copyright (C) 2015 - 2017 Microscene Inc., All Rights Reserved.
 *
 */
package com.vizen.sd.repository.mysql.domain;

import com.vizen.framework.mybatis.BaseModel;
import java.io.Serializable;
import java.util.Date;

/**
 *
 * @author mark@visualbusiness.com
 * @date 2017-12-26
 *
 */
public class PanoStitch extends BaseModel implements Serializable {
    private String id;

    private String name;

    private Integer isSuccess;

    private Integer deviceType;

    /**
     * json字符串key为图片位置下标, value为{'url':'', 'name':''}
     */
    private String stitch;

    private Long creatorId;

    private Date createTime;

    private Long updaterId;

    private Date updateTime;

    /**
     * 调用拼接任务开始时间
     */
    private Date beginTime;

    /**
     * 预计处理等待时间
     */
    private Long waitingTime;

    /**
     * 拼接任务结束时间
     */
    private Date finishTime;

    /**
     * 逻辑删除标识(0无效:,1:有效)
     */
    private Integer isValid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pano_stitch
     */
    private static final long serialVersionUID = 1L;

    /**
     * @return id
     */
    public String getId() {
        return id;
    }

    /**
     * @param id
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * @return name
     */
    public String getName() {
        return name;
    }

    /**
     * @param name
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * @return is_success
     */
    public Integer getIsSuccess() {
        return isSuccess;
    }

    /**
     * @param isSuccess
     */
    public void setIsSuccess(Integer isSuccess) {
        this.isSuccess = isSuccess;
    }

    /**
     * @return device_type
     */
    public Integer getDeviceType() {
        return deviceType;
    }

    /**
     * @param deviceType
     */
    public void setDeviceType(Integer deviceType) {
        this.deviceType = deviceType;
    }

    /**
     * 获取json字符串key为图片位置下标, value为{'url':'', 'name':''}
     *
     * @return stitch - json字符串key为图片位置下标, value为{'url':'', 'name':''}
     */
    public String getStitch() {
        return stitch;
    }

    /**
     * 设置json字符串key为图片位置下标, value为{'url':'', 'name':''}
     *
     * @param stitch json字符串key为图片位置下标, value为{'url':'', 'name':''}
     */
    public void setStitch(String stitch) {
        this.stitch = stitch == null ? null : stitch.trim();
    }

    /**
     * @return creator_id
     */
    public Long getCreatorId() {
        return creatorId;
    }

    /**
     * @param creatorId
     */
    public void setCreatorId(Long creatorId) {
        this.creatorId = creatorId;
    }

    /**
     * @return create_time
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * @param createTime
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * @return updater_id
     */
    public Long getUpdaterId() {
        return updaterId;
    }

    /**
     * @param updaterId
     */
    public void setUpdaterId(Long updaterId) {
        this.updaterId = updaterId;
    }

    /**
     * @return update_time
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * @param updateTime
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * 获取调用拼接任务开始时间
     *
     * @return begin_time - 调用拼接任务开始时间
     */
    public Date getBeginTime() {
        return beginTime;
    }

    /**
     * 设置调用拼接任务开始时间
     *
     * @param beginTime 调用拼接任务开始时间
     */
    public void setBeginTime(Date beginTime) {
        this.beginTime = beginTime;
    }

    /**
     * 获取预计处理等待时间
     *
     * @return waiting_time - 预计处理等待时间
     */
    public Long getWaitingTime() {
        return waitingTime;
    }

    /**
     * 设置预计处理等待时间
     *
     * @param waitingTime 预计处理等待时间
     */
    public void setWaitingTime(Long waitingTime) {
        this.waitingTime = waitingTime;
    }

    /**
     * 获取拼接任务结束时间
     *
     * @return finish_time - 拼接任务结束时间
     */
    public Date getFinishTime() {
        return finishTime;
    }

    /**
     * 设置拼接任务结束时间
     *
     * @param finishTime 拼接任务结束时间
     */
    public void setFinishTime(Date finishTime) {
        this.finishTime = finishTime;
    }

    /**
     * 获取逻辑删除标识(0无效:,1:有效)
     *
     * @return is_valid - 逻辑删除标识(0无效:,1:有效)
     */
    public Integer getIsValid() {
        return isValid;
    }

    /**
     * 设置逻辑删除标识(0无效:,1:有效)
     *
     * @param isValid 逻辑删除标识(0无效:,1:有效)
     */
    public void setIsValid(Integer isValid) {
        this.isValid = isValid;
    }

    @Override
    public String toString() {
        return "PanoStitch [id=" + id + ",name=" + name + ",isSuccess=" + isSuccess + ",deviceType=" + deviceType + ",stitch=" + stitch + ",creatorId=" + creatorId + ",createTime=" + createTime + ",updaterId=" + updaterId + ",updateTime=" + updateTime + ",beginTime=" + beginTime + ",waitingTime=" + waitingTime + ",finishTime=" + finishTime + ",isValid=" + isValid + "->" + super.toString() + "]";
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pano_stitch
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        PanoStitch other = (PanoStitch) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getIsSuccess() == null ? other.getIsSuccess() == null : this.getIsSuccess().equals(other.getIsSuccess()))
            && (this.getDeviceType() == null ? other.getDeviceType() == null : this.getDeviceType().equals(other.getDeviceType()))
            && (this.getStitch() == null ? other.getStitch() == null : this.getStitch().equals(other.getStitch()))
            && (this.getCreatorId() == null ? other.getCreatorId() == null : this.getCreatorId().equals(other.getCreatorId()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdaterId() == null ? other.getUpdaterId() == null : this.getUpdaterId().equals(other.getUpdaterId()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getBeginTime() == null ? other.getBeginTime() == null : this.getBeginTime().equals(other.getBeginTime()))
            && (this.getWaitingTime() == null ? other.getWaitingTime() == null : this.getWaitingTime().equals(other.getWaitingTime()))
            && (this.getFinishTime() == null ? other.getFinishTime() == null : this.getFinishTime().equals(other.getFinishTime()))
            && (this.getIsValid() == null ? other.getIsValid() == null : this.getIsValid().equals(other.getIsValid()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pano_stitch
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getIsSuccess() == null) ? 0 : getIsSuccess().hashCode());
        result = prime * result + ((getDeviceType() == null) ? 0 : getDeviceType().hashCode());
        result = prime * result + ((getStitch() == null) ? 0 : getStitch().hashCode());
        result = prime * result + ((getCreatorId() == null) ? 0 : getCreatorId().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdaterId() == null) ? 0 : getUpdaterId().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getBeginTime() == null) ? 0 : getBeginTime().hashCode());
        result = prime * result + ((getWaitingTime() == null) ? 0 : getWaitingTime().hashCode());
        result = prime * result + ((getFinishTime() == null) ? 0 : getFinishTime().hashCode());
        result = prime * result + ((getIsValid() == null) ? 0 : getIsValid().hashCode());
        return result;
    }
}