{
    "info": [
        { "id":101, "type": "week","name":"朱子治家格言（一）"},
        { "id":102, "type": "week","name":"朱子治家格言（二）"},
        { "id":103, "type": "week","name":"朱子治家格言（三）"},
        { "id":104, "type": "week","name":"朱子治家格言（四）"},
        { "id":105, "type": "month","name":"《朱子治家格言》"},
        { "id":106, "type": "week","name":"弟子规（一）"},
        { "id":107, "type": "week","name":"弟子规（二）"},
        { "id":108, "type": "week","name":"弟子规（三）"},
        { "id":109, "type": "week","name":"弟子规（四）"},
        { "id":110, "type": "month","name":"弟子规"},
        { "id":111, "type": "week","name":"道德经（一）"},
        { "id":112, "type": "week","name":"道德经（二）"},
        { "id":113, "type": "week","name":"道德经（三）"},
        { "id":114, "type": "week","name":"道德经（四）"},
        { "id":115, "type": "month","name": "道德经" },
        { "id":116, "type": "week","name": "论语.学而第一（一）" }, 
	{ "id":117, "type": "week","name": "论语.学而第一（二）" }, 
	{ "id":118, "type": "week","name": "论语.学而第一（三）" }, 
	{ "id":119, "type": "week","name": "论语.学而第一（四）" }, 
	{ "id":120, "type": "month","name": "论语.学而第一" },
	{ "id":123, "type": "week","name": "孝经.上（一）" },
	{ "id":124, "type": "week","name": "孝经.上（二）" },
	{ "id":125, "type": "week","name": "孝经.上（三）" },
	{ "id":126, "type": "week","name": "孝经.上（四）" },
	{ "id":127, "type": "month","name": "孝经.上" },
	{ "id":128, "type": "week","name": "孝经.下（一）" },
	{ "id":129, "type": "week","name": "孝经.下（二）" },
	{ "id":130, "type": "week","name": "孝经.下（三）" },
	{ "id":131, "type": "week","name": "孝经.下（四）" },
	{ "id":132, "type": "month","name": "孝经.下" },
        { "id":133, "type": "week","name": "大学（上）（一）" },
	{ "id":134, "type": "week","name": "大学（上）（二）" },
	{ "id":135, "type": "week","name": "大学（上）（三）" },
	{ "id":136, "type": "week","name": "大学（上）（四）" },
	{ "id":137, "type": "month","name": "大学（上）" },
        { "id":138, "type": "week","name": "大学（中）（一）" },
        { "id":139, "type": "week","name": "大学（中）（二）" },
        { "id":140, "type": "week","name": "大学（中）（三）" },
        { "id":141, "type": "week","name": "大学（中）（四）" },
        { "id":142, "type": "month","name": "大学（中）" },
	{ "id":143, "type": "week","name": "大学（下）（一）" },
        { "id":144, "type": "week","name": "大学（下）（二）" },
        { "id":145, "type": "week","name": "大学（下）（三）" },
        { "id":146, "type": "week","name": "大学（下）（四）" },
        { "id":148, "type": "month","name": "大学（下）" },
	{ "id":150, "type": "week","name": "中庸（上）（一）" },
        { "id":151, "type": "week","name": "中庸（上）（二）" },
        { "id":152, "type": "week","name": "中庸（上）（三）" },
        { "id":153, "type": "week","name": "中庸（上）（四）" },
        { "id":154, "type": "month","name": "中庸（上）" }
    ]
}