/*
 * Copyright (C) 2015 - 2017 Microscene Inc., All Rights Reserved.
 *
 */
package com.vizen.sd.repository.mysql.domain;

import com.vizen.framework.mybatis.BaseModel;
import java.io.Serializable;

/**
 *
 * @author mark@visualbusiness.com
 * @date 2017-12-20
 *
 */
public class GridJump extends BaseModel implements Serializable {
    private Long id;

    /**
     * 跳转标记
     */
    private String jumpMark;

    /**
     * 跳转的下一网格id
     */
    private Long jumpGridId;

    /**
     * 跳转的下一网格code
     */
    private String jumpGridCode;

    /**
     * 跳转的下一全景id
     */
    private String jumpPanoId;

    /**
     * 跳转的下一全景名
     */
    private String jumpPanoName;

    /**
     * 跳转点位置
     */
    private String position;

    /**
     * 当前网格id
     */
    private Long gridId;

    /**
     * 当前网格code
     */
    private String gridCode;

    private Long projcetId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table grid_jump
     */
    private static final long serialVersionUID = 1L;

    /**
     * @return id
     */
    public Long getId() {
        return id;
    }

    /**
     * @param id
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 获取跳转标记
     *
     * @return jump_mark - 跳转标记
     */
    public String getJumpMark() {
        return jumpMark;
    }

    /**
     * 设置跳转标记
     *
     * @param jumpMark 跳转标记
     */
    public void setJumpMark(String jumpMark) {
        this.jumpMark = jumpMark == null ? null : jumpMark.trim();
    }

    /**
     * 获取跳转的下一网格id
     *
     * @return jump_grid_id - 跳转的下一网格id
     */
    public Long getJumpGridId() {
        return jumpGridId;
    }

    /**
     * 设置跳转的下一网格id
     *
     * @param jumpGridId 跳转的下一网格id
     */
    public void setJumpGridId(Long jumpGridId) {
        this.jumpGridId = jumpGridId;
    }

    /**
     * 获取跳转的下一网格code
     *
     * @return jump_grid_code - 跳转的下一网格code
     */
    public String getJumpGridCode() {
        return jumpGridCode;
    }

    /**
     * 设置跳转的下一网格code
     *
     * @param jumpGridCode 跳转的下一网格code
     */
    public void setJumpGridCode(String jumpGridCode) {
        this.jumpGridCode = jumpGridCode == null ? null : jumpGridCode.trim();
    }

    /**
     * 获取跳转的下一全景id
     *
     * @return jump_pano_id - 跳转的下一全景id
     */
    public String getJumpPanoId() {
        return jumpPanoId;
    }

    /**
     * 设置跳转的下一全景id
     *
     * @param jumpPanoId 跳转的下一全景id
     */
    public void setJumpPanoId(String jumpPanoId) {
        this.jumpPanoId = jumpPanoId == null ? null : jumpPanoId.trim();
    }

    /**
     * 获取跳转的下一全景名
     *
     * @return jump_pano_name - 跳转的下一全景名
     */
    public String getJumpPanoName() {
        return jumpPanoName;
    }

    /**
     * 设置跳转的下一全景名
     *
     * @param jumpPanoName 跳转的下一全景名
     */
    public void setJumpPanoName(String jumpPanoName) {
        this.jumpPanoName = jumpPanoName == null ? null : jumpPanoName.trim();
    }

    /**
     * 获取跳转点位置
     *
     * @return position - 跳转点位置
     */
    public String getPosition() {
        return position;
    }

    /**
     * 设置跳转点位置
     *
     * @param position 跳转点位置
     */
    public void setPosition(String position) {
        this.position = position == null ? null : position.trim();
    }

    /**
     * 获取当前网格id
     *
     * @return grid_id - 当前网格id
     */
    public Long getGridId() {
        return gridId;
    }

    /**
     * 设置当前网格id
     *
     * @param gridId 当前网格id
     */
    public void setGridId(Long gridId) {
        this.gridId = gridId;
    }

    /**
     * 获取当前网格code
     *
     * @return grid_code - 当前网格code
     */
    public String getGridCode() {
        return gridCode;
    }

    /**
     * 设置当前网格code
     *
     * @param gridCode 当前网格code
     */
    public void setGridCode(String gridCode) {
        this.gridCode = gridCode == null ? null : gridCode.trim();
    }

    /**
     * @return projcet_id
     */
    public Long getProjcetId() {
        return projcetId;
    }

    /**
     * @param projcetId
     */
    public void setProjcetId(Long projcetId) {
        this.projcetId = projcetId;
    }

    @Override
    public String toString() {
        return "GridJump [id=" + id + ",jumpMark=" + jumpMark + ",jumpGridId=" + jumpGridId + ",jumpGridCode=" + jumpGridCode + ",jumpPanoId=" + jumpPanoId + ",jumpPanoName=" + jumpPanoName + ",position=" + position + ",gridId=" + gridId + ",gridCode=" + gridCode + ",projcetId=" + projcetId + "->" + super.toString() + "]";
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grid_jump
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        GridJump other = (GridJump) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getJumpMark() == null ? other.getJumpMark() == null : this.getJumpMark().equals(other.getJumpMark()))
            && (this.getJumpGridId() == null ? other.getJumpGridId() == null : this.getJumpGridId().equals(other.getJumpGridId()))
            && (this.getJumpGridCode() == null ? other.getJumpGridCode() == null : this.getJumpGridCode().equals(other.getJumpGridCode()))
            && (this.getJumpPanoId() == null ? other.getJumpPanoId() == null : this.getJumpPanoId().equals(other.getJumpPanoId()))
            && (this.getJumpPanoName() == null ? other.getJumpPanoName() == null : this.getJumpPanoName().equals(other.getJumpPanoName()))
            && (this.getPosition() == null ? other.getPosition() == null : this.getPosition().equals(other.getPosition()))
            && (this.getGridId() == null ? other.getGridId() == null : this.getGridId().equals(other.getGridId()))
            && (this.getGridCode() == null ? other.getGridCode() == null : this.getGridCode().equals(other.getGridCode()))
            && (this.getProjcetId() == null ? other.getProjcetId() == null : this.getProjcetId().equals(other.getProjcetId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grid_jump
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getJumpMark() == null) ? 0 : getJumpMark().hashCode());
        result = prime * result + ((getJumpGridId() == null) ? 0 : getJumpGridId().hashCode());
        result = prime * result + ((getJumpGridCode() == null) ? 0 : getJumpGridCode().hashCode());
        result = prime * result + ((getJumpPanoId() == null) ? 0 : getJumpPanoId().hashCode());
        result = prime * result + ((getJumpPanoName() == null) ? 0 : getJumpPanoName().hashCode());
        result = prime * result + ((getPosition() == null) ? 0 : getPosition().hashCode());
        result = prime * result + ((getGridId() == null) ? 0 : getGridId().hashCode());
        result = prime * result + ((getGridCode() == null) ? 0 : getGridCode().hashCode());
        result = prime * result + ((getProjcetId() == null) ? 0 : getProjcetId().hashCode());
        return result;
    }
}