/*
 * Copyright (C) 2015 - 2017 Microscene Inc., All Rights Reserved.
 *
 */
package com.vizen.sd.repository.mysql.domain;

import com.vizen.framework.mybatis.BaseModel;
import java.io.Serializable;
import java.util.Date;

/**
 *
 * @author mark@visualbusiness.com
 * @date 2017-12-26
 *
 */
public class Poi extends BaseModel implements Serializable {
    private String id;

    private String name;

    private String desc;

    private String provinceId;

    private String cityId;

    private String countyId;

    private String areaId;

    /**
     * 坐标系
     */
    private Integer coordsys;

    /**
     * 经纬度
     */
    private String lnglat;

    /**
     * 纬度
     */
    private Long lat;

    /**
     * 经度
     */
    private Long lng;

    /**
     * 朝向
     */
    private String direction;

    /**
     * 高度
     */
    private Integer height;

    /**
     * 拍摄方式
     */
    private Integer cameraType;

    /**
     * 拍摄时间
     */
    private Date photoTime;

    /**
     * 封面
     */
    private String thumbnail;

    private String creatorId;

    private Date createTime;

    private String updaterId;

    private Date updateYime;

    private String tag;

    private String panoId;

    /**
     * cos上存储的文件名
     */
    private String fileName;

    /**
     * 上传状态 ，1 完成  0 未完成
     */
    private Integer isFinish;

    /**
     * 逻辑删除标识(0无效:,1:有效)
     */
    private Integer isValid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table poi
     */
    private static final long serialVersionUID = 1L;

    /**
     * @return id
     */
    public String getId() {
        return id;
    }

    /**
     * @param id
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * @return name
     */
    public String getName() {
        return name;
    }

    /**
     * @param name
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * @return desc
     */
    public String getDesc() {
        return desc;
    }

    /**
     * @param desc
     */
    public void setDesc(String desc) {
        this.desc = desc == null ? null : desc.trim();
    }

    /**
     * @return province_id
     */
    public String getProvinceId() {
        return provinceId;
    }

    /**
     * @param provinceId
     */
    public void setProvinceId(String provinceId) {
        this.provinceId = provinceId == null ? null : provinceId.trim();
    }

    /**
     * @return city_id
     */
    public String getCityId() {
        return cityId;
    }

    /**
     * @param cityId
     */
    public void setCityId(String cityId) {
        this.cityId = cityId == null ? null : cityId.trim();
    }

    /**
     * @return county_id
     */
    public String getCountyId() {
        return countyId;
    }

    /**
     * @param countyId
     */
    public void setCountyId(String countyId) {
        this.countyId = countyId == null ? null : countyId.trim();
    }

    /**
     * @return area_id
     */
    public String getAreaId() {
        return areaId;
    }

    /**
     * @param areaId
     */
    public void setAreaId(String areaId) {
        this.areaId = areaId == null ? null : areaId.trim();
    }

    /**
     * 获取坐标系
     *
     * @return coordsys - 坐标系
     */
    public Integer getCoordsys() {
        return coordsys;
    }

    /**
     * 设置坐标系
     *
     * @param coordsys 坐标系
     */
    public void setCoordsys(Integer coordsys) {
        this.coordsys = coordsys;
    }

    /**
     * 获取经纬度
     *
     * @return lnglat - 经纬度
     */
    public String getLnglat() {
        return lnglat;
    }

    /**
     * 设置经纬度
     *
     * @param lnglat 经纬度
     */
    public void setLnglat(String lnglat) {
        this.lnglat = lnglat == null ? null : lnglat.trim();
    }

    /**
     * 获取纬度
     *
     * @return lat - 纬度
     */
    public Long getLat() {
        return lat;
    }

    /**
     * 设置纬度
     *
     * @param lat 纬度
     */
    public void setLat(Long lat) {
        this.lat = lat;
    }

    /**
     * 获取经度
     *
     * @return lng - 经度
     */
    public Long getLng() {
        return lng;
    }

    /**
     * 设置经度
     *
     * @param lng 经度
     */
    public void setLng(Long lng) {
        this.lng = lng;
    }

    /**
     * 获取朝向
     *
     * @return direction - 朝向
     */
    public String getDirection() {
        return direction;
    }

    /**
     * 设置朝向
     *
     * @param direction 朝向
     */
    public void setDirection(String direction) {
        this.direction = direction == null ? null : direction.trim();
    }

    /**
     * 获取高度
     *
     * @return height - 高度
     */
    public Integer getHeight() {
        return height;
    }

    /**
     * 设置高度
     *
     * @param height 高度
     */
    public void setHeight(Integer height) {
        this.height = height;
    }

    /**
     * 获取拍摄方式
     *
     * @return camera_type - 拍摄方式
     */
    public Integer getCameraType() {
        return cameraType;
    }

    /**
     * 设置拍摄方式
     *
     * @param cameraType 拍摄方式
     */
    public void setCameraType(Integer cameraType) {
        this.cameraType = cameraType;
    }

    /**
     * 获取拍摄时间
     *
     * @return photo_time - 拍摄时间
     */
    public Date getPhotoTime() {
        return photoTime;
    }

    /**
     * 设置拍摄时间
     *
     * @param photoTime 拍摄时间
     */
    public void setPhotoTime(Date photoTime) {
        this.photoTime = photoTime;
    }

    /**
     * 获取封面
     *
     * @return thumbnail - 封面
     */
    public String getThumbnail() {
        return thumbnail;
    }

    /**
     * 设置封面
     *
     * @param thumbnail 封面
     */
    public void setThumbnail(String thumbnail) {
        this.thumbnail = thumbnail == null ? null : thumbnail.trim();
    }

    /**
     * @return creator_id
     */
    public String getCreatorId() {
        return creatorId;
    }

    /**
     * @param creatorId
     */
    public void setCreatorId(String creatorId) {
        this.creatorId = creatorId == null ? null : creatorId.trim();
    }

    /**
     * @return create_time
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * @param createTime
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * @return updater_id
     */
    public String getUpdaterId() {
        return updaterId;
    }

    /**
     * @param updaterId
     */
    public void setUpdaterId(String updaterId) {
        this.updaterId = updaterId == null ? null : updaterId.trim();
    }

    /**
     * @return update_yime
     */
    public Date getUpdateYime() {
        return updateYime;
    }

    /**
     * @param updateYime
     */
    public void setUpdateYime(Date updateYime) {
        this.updateYime = updateYime;
    }

    /**
     * @return tag
     */
    public String getTag() {
        return tag;
    }

    /**
     * @param tag
     */
    public void setTag(String tag) {
        this.tag = tag == null ? null : tag.trim();
    }

    /**
     * @return pano_id
     */
    public String getPanoId() {
        return panoId;
    }

    /**
     * @param panoId
     */
    public void setPanoId(String panoId) {
        this.panoId = panoId == null ? null : panoId.trim();
    }

    /**
     * 获取cos上存储的文件名
     *
     * @return file_name - cos上存储的文件名
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * 设置cos上存储的文件名
     *
     * @param fileName cos上存储的文件名
     */
    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }

    /**
     * 获取上传状态 ，1 完成  0 未完成
     *
     * @return is_finish - 上传状态 ，1 完成  0 未完成
     */
    public Integer getIsFinish() {
        return isFinish;
    }

    /**
     * 设置上传状态 ，1 完成  0 未完成
     *
     * @param isFinish 上传状态 ，1 完成  0 未完成
     */
    public void setIsFinish(Integer isFinish) {
        this.isFinish = isFinish;
    }

    /**
     * 获取逻辑删除标识(0无效:,1:有效)
     *
     * @return is_valid - 逻辑删除标识(0无效:,1:有效)
     */
    public Integer getIsValid() {
        return isValid;
    }

    /**
     * 设置逻辑删除标识(0无效:,1:有效)
     *
     * @param isValid 逻辑删除标识(0无效:,1:有效)
     */
    public void setIsValid(Integer isValid) {
        this.isValid = isValid;
    }

    @Override
    public String toString() {
        return "Poi [id=" + id + ",name=" + name + ",desc=" + desc + ",provinceId=" + provinceId + ",cityId=" + cityId + ",countyId=" + countyId + ",areaId=" + areaId + ",coordsys=" + coordsys + ",lnglat=" + lnglat + ",lat=" + lat + ",lng=" + lng + ",direction=" + direction + ",height=" + height + ",cameraType=" + cameraType + ",photoTime=" + photoTime + ",thumbnail=" + thumbnail + ",creatorId=" + creatorId + ",createTime=" + createTime + ",updaterId=" + updaterId + ",updateYime=" + updateYime + ",tag=" + tag + ",panoId=" + panoId + ",fileName=" + fileName + ",isFinish=" + isFinish + ",isValid=" + isValid + "->" + super.toString() + "]";
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poi
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Poi other = (Poi) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getDesc() == null ? other.getDesc() == null : this.getDesc().equals(other.getDesc()))
            && (this.getProvinceId() == null ? other.getProvinceId() == null : this.getProvinceId().equals(other.getProvinceId()))
            && (this.getCityId() == null ? other.getCityId() == null : this.getCityId().equals(other.getCityId()))
            && (this.getCountyId() == null ? other.getCountyId() == null : this.getCountyId().equals(other.getCountyId()))
            && (this.getAreaId() == null ? other.getAreaId() == null : this.getAreaId().equals(other.getAreaId()))
            && (this.getCoordsys() == null ? other.getCoordsys() == null : this.getCoordsys().equals(other.getCoordsys()))
            && (this.getLnglat() == null ? other.getLnglat() == null : this.getLnglat().equals(other.getLnglat()))
            && (this.getLat() == null ? other.getLat() == null : this.getLat().equals(other.getLat()))
            && (this.getLng() == null ? other.getLng() == null : this.getLng().equals(other.getLng()))
            && (this.getDirection() == null ? other.getDirection() == null : this.getDirection().equals(other.getDirection()))
            && (this.getHeight() == null ? other.getHeight() == null : this.getHeight().equals(other.getHeight()))
            && (this.getCameraType() == null ? other.getCameraType() == null : this.getCameraType().equals(other.getCameraType()))
            && (this.getPhotoTime() == null ? other.getPhotoTime() == null : this.getPhotoTime().equals(other.getPhotoTime()))
            && (this.getThumbnail() == null ? other.getThumbnail() == null : this.getThumbnail().equals(other.getThumbnail()))
            && (this.getCreatorId() == null ? other.getCreatorId() == null : this.getCreatorId().equals(other.getCreatorId()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdaterId() == null ? other.getUpdaterId() == null : this.getUpdaterId().equals(other.getUpdaterId()))
            && (this.getUpdateYime() == null ? other.getUpdateYime() == null : this.getUpdateYime().equals(other.getUpdateYime()))
            && (this.getTag() == null ? other.getTag() == null : this.getTag().equals(other.getTag()))
            && (this.getPanoId() == null ? other.getPanoId() == null : this.getPanoId().equals(other.getPanoId()))
            && (this.getFileName() == null ? other.getFileName() == null : this.getFileName().equals(other.getFileName()))
            && (this.getIsFinish() == null ? other.getIsFinish() == null : this.getIsFinish().equals(other.getIsFinish()))
            && (this.getIsValid() == null ? other.getIsValid() == null : this.getIsValid().equals(other.getIsValid()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poi
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getDesc() == null) ? 0 : getDesc().hashCode());
        result = prime * result + ((getProvinceId() == null) ? 0 : getProvinceId().hashCode());
        result = prime * result + ((getCityId() == null) ? 0 : getCityId().hashCode());
        result = prime * result + ((getCountyId() == null) ? 0 : getCountyId().hashCode());
        result = prime * result + ((getAreaId() == null) ? 0 : getAreaId().hashCode());
        result = prime * result + ((getCoordsys() == null) ? 0 : getCoordsys().hashCode());
        result = prime * result + ((getLnglat() == null) ? 0 : getLnglat().hashCode());
        result = prime * result + ((getLat() == null) ? 0 : getLat().hashCode());
        result = prime * result + ((getLng() == null) ? 0 : getLng().hashCode());
        result = prime * result + ((getDirection() == null) ? 0 : getDirection().hashCode());
        result = prime * result + ((getHeight() == null) ? 0 : getHeight().hashCode());
        result = prime * result + ((getCameraType() == null) ? 0 : getCameraType().hashCode());
        result = prime * result + ((getPhotoTime() == null) ? 0 : getPhotoTime().hashCode());
        result = prime * result + ((getThumbnail() == null) ? 0 : getThumbnail().hashCode());
        result = prime * result + ((getCreatorId() == null) ? 0 : getCreatorId().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdaterId() == null) ? 0 : getUpdaterId().hashCode());
        result = prime * result + ((getUpdateYime() == null) ? 0 : getUpdateYime().hashCode());
        result = prime * result + ((getTag() == null) ? 0 : getTag().hashCode());
        result = prime * result + ((getPanoId() == null) ? 0 : getPanoId().hashCode());
        result = prime * result + ((getFileName() == null) ? 0 : getFileName().hashCode());
        result = prime * result + ((getIsFinish() == null) ? 0 : getIsFinish().hashCode());
        result = prime * result + ((getIsValid() == null) ? 0 : getIsValid().hashCode());
        return result;
    }
}