/*
 * Copyright (C) 2015 - 2017 Microscene Inc., All Rights Reserved.
 *
 */
package com.vizen.sd.repository.mysql.domain;

import com.vizen.framework.mybatis.BaseModel;
import java.io.Serializable;
import java.util.Date;

/**
 *
 * @author mark@visualbusiness.com
 * @date 2017-12-20
 *
 */
public class Resource extends BaseModel implements Serializable {
    private Long resourceId;

    /**
     * 资源名称
     */
    private String resourceName;

    /**
     * 菜单名称
     */
    private Long menuId;

    /**
     * 资源uri
     */
    private String uriPattern;

    /**
     * 状态
     */
    private Integer status;

    /**
     * 创建时间
     */
    private Date createTime;

    /**
     * 逻辑删除标识(0无效:,1:有效)
     */
    private Byte isValid;

    private String methodType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table resource
     */
    private static final long serialVersionUID = 1L;

    /**
     * @return resource_id
     */
    public Long getResourceId() {
        return resourceId;
    }

    /**
     * @param resourceId
     */
    public void setResourceId(Long resourceId) {
        this.resourceId = resourceId;
    }

    /**
     * 获取资源名称
     *
     * @return resource_name - 资源名称
     */
    public String getResourceName() {
        return resourceName;
    }

    /**
     * 设置资源名称
     *
     * @param resourceName 资源名称
     */
    public void setResourceName(String resourceName) {
        this.resourceName = resourceName == null ? null : resourceName.trim();
    }

    /**
     * 获取菜单名称
     *
     * @return menu_id - 菜单名称
     */
    public Long getMenuId() {
        return menuId;
    }

    /**
     * 设置菜单名称
     *
     * @param menuId 菜单名称
     */
    public void setMenuId(Long menuId) {
        this.menuId = menuId;
    }

    /**
     * 获取资源uri
     *
     * @return uri_pattern - 资源uri
     */
    public String getUriPattern() {
        return uriPattern;
    }

    /**
     * 设置资源uri
     *
     * @param uriPattern 资源uri
     */
    public void setUriPattern(String uriPattern) {
        this.uriPattern = uriPattern == null ? null : uriPattern.trim();
    }

    /**
     * 获取状态
     *
     * @return status - 状态
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * 设置状态
     *
     * @param status 状态
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * 获取创建时间
     *
     * @return create_time - 创建时间
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * 设置创建时间
     *
     * @param createTime 创建时间
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * 获取逻辑删除标识(0无效:,1:有效)
     *
     * @return is_valid - 逻辑删除标识(0无效:,1:有效)
     */
    public Byte getIsValid() {
        return isValid;
    }

    /**
     * 设置逻辑删除标识(0无效:,1:有效)
     *
     * @param isValid 逻辑删除标识(0无效:,1:有效)
     */
    public void setIsValid(Byte isValid) {
        this.isValid = isValid;
    }

    /**
     * @return method_type
     */
    public String getMethodType() {
        return methodType;
    }

    /**
     * @param methodType
     */
    public void setMethodType(String methodType) {
        this.methodType = methodType == null ? null : methodType.trim();
    }

    @Override
    public String toString() {
        return "Resource [resourceId=" + resourceId + ",resourceName=" + resourceName + ",menuId=" + menuId + ",uriPattern=" + uriPattern + ",status=" + status + ",createTime=" + createTime + ",isValid=" + isValid + ",methodType=" + methodType + "->" + super.toString() + "]";
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Resource other = (Resource) that;
        return (this.getResourceId() == null ? other.getResourceId() == null : this.getResourceId().equals(other.getResourceId()))
            && (this.getResourceName() == null ? other.getResourceName() == null : this.getResourceName().equals(other.getResourceName()))
            && (this.getMenuId() == null ? other.getMenuId() == null : this.getMenuId().equals(other.getMenuId()))
            && (this.getUriPattern() == null ? other.getUriPattern() == null : this.getUriPattern().equals(other.getUriPattern()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getIsValid() == null ? other.getIsValid() == null : this.getIsValid().equals(other.getIsValid()))
            && (this.getMethodType() == null ? other.getMethodType() == null : this.getMethodType().equals(other.getMethodType()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getResourceId() == null) ? 0 : getResourceId().hashCode());
        result = prime * result + ((getResourceName() == null) ? 0 : getResourceName().hashCode());
        result = prime * result + ((getMenuId() == null) ? 0 : getMenuId().hashCode());
        result = prime * result + ((getUriPattern() == null) ? 0 : getUriPattern().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getIsValid() == null) ? 0 : getIsValid().hashCode());
        result = prime * result + ((getMethodType() == null) ? 0 : getMethodType().hashCode());
        return result;
    }
}