/*
 * Copyright (C) 2015 - 2017 Microscene Inc., All Rights Reserved.
 *
 */
package com.vizen.sd.repository.mysql.domain;

import com.vizen.framework.mybatis.BaseModel;
import java.io.Serializable;
import java.util.Date;

/**
 *
 * @author mark@visualbusiness.com
 * @date 2017-12-20
 *
 */
public class ThreeDimensional extends BaseModel implements Serializable {
    private String threeDimensionalId;

    /**
     * 名称
     */
    private String threeDimensionalName;

    /**
     * 面积
     */
    private Long area;

    /**
     * 分辨率(厘米)
     */
    private Long resolutionRatio;

    /**
     * 纬度
     */
    private String latitude;

    /**
     * 经度
     */
    private String longitude;

    /**
     * 描述
     */
    private String description;

    /**
     * 缩略图url
     */
    private String thumbnailUrl;

    /**
     * 二维码url
     */
    private String qrcodeUrl;

    /**
     * 逻辑删除标识(0无效:,1:有效)
     */
    private Byte isValid;

    /**
     * 创建时间
     */
    private Date createTime;

    /**
     * 修改时间
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table three_dimensional
     */
    private static final long serialVersionUID = 1L;

    /**
     * @return three_dimensional_id
     */
    public String getThreeDimensionalId() {
        return threeDimensionalId;
    }

    /**
     * @param threeDimensionalId
     */
    public void setThreeDimensionalId(String threeDimensionalId) {
        this.threeDimensionalId = threeDimensionalId == null ? null : threeDimensionalId.trim();
    }

    /**
     * 获取名称
     *
     * @return three_dimensional_name - 名称
     */
    public String getThreeDimensionalName() {
        return threeDimensionalName;
    }

    /**
     * 设置名称
     *
     * @param threeDimensionalName 名称
     */
    public void setThreeDimensionalName(String threeDimensionalName) {
        this.threeDimensionalName = threeDimensionalName == null ? null : threeDimensionalName.trim();
    }

    /**
     * 获取面积
     *
     * @return area - 面积
     */
    public Long getArea() {
        return area;
    }

    /**
     * 设置面积
     *
     * @param area 面积
     */
    public void setArea(Long area) {
        this.area = area;
    }

    /**
     * 获取分辨率(厘米)
     *
     * @return resolution_ratio - 分辨率(厘米)
     */
    public Long getResolutionRatio() {
        return resolutionRatio;
    }

    /**
     * 设置分辨率(厘米)
     *
     * @param resolutionRatio 分辨率(厘米)
     */
    public void setResolutionRatio(Long resolutionRatio) {
        this.resolutionRatio = resolutionRatio;
    }

    /**
     * 获取纬度
     *
     * @return latitude - 纬度
     */
    public String getLatitude() {
        return latitude;
    }

    /**
     * 设置纬度
     *
     * @param latitude 纬度
     */
    public void setLatitude(String latitude) {
        this.latitude = latitude == null ? null : latitude.trim();
    }

    /**
     * 获取经度
     *
     * @return longitude - 经度
     */
    public String getLongitude() {
        return longitude;
    }

    /**
     * 设置经度
     *
     * @param longitude 经度
     */
    public void setLongitude(String longitude) {
        this.longitude = longitude == null ? null : longitude.trim();
    }

    /**
     * 获取描述
     *
     * @return description - 描述
     */
    public String getDescription() {
        return description;
    }

    /**
     * 设置描述
     *
     * @param description 描述
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * 获取缩略图url
     *
     * @return thumbnail_url - 缩略图url
     */
    public String getThumbnailUrl() {
        return thumbnailUrl;
    }

    /**
     * 设置缩略图url
     *
     * @param thumbnailUrl 缩略图url
     */
    public void setThumbnailUrl(String thumbnailUrl) {
        this.thumbnailUrl = thumbnailUrl == null ? null : thumbnailUrl.trim();
    }

    /**
     * 获取二维码url
     *
     * @return qrcode_url - 二维码url
     */
    public String getQrcodeUrl() {
        return qrcodeUrl;
    }

    /**
     * 设置二维码url
     *
     * @param qrcodeUrl 二维码url
     */
    public void setQrcodeUrl(String qrcodeUrl) {
        this.qrcodeUrl = qrcodeUrl == null ? null : qrcodeUrl.trim();
    }

    /**
     * 获取逻辑删除标识(0无效:,1:有效)
     *
     * @return is_valid - 逻辑删除标识(0无效:,1:有效)
     */
    public Byte getIsValid() {
        return isValid;
    }

    /**
     * 设置逻辑删除标识(0无效:,1:有效)
     *
     * @param isValid 逻辑删除标识(0无效:,1:有效)
     */
    public void setIsValid(Byte isValid) {
        this.isValid = isValid;
    }

    /**
     * 获取创建时间
     *
     * @return create_time - 创建时间
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * 设置创建时间
     *
     * @param createTime 创建时间
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * 获取修改时间
     *
     * @return modify_time - 修改时间
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * 设置修改时间
     *
     * @param modifyTime 修改时间
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    @Override
    public String toString() {
        return "ThreeDimensional [threeDimensionalId=" + threeDimensionalId + ",threeDimensionalName=" + threeDimensionalName + ",area=" + area + ",resolutionRatio=" + resolutionRatio + ",latitude=" + latitude + ",longitude=" + longitude + ",description=" + description + ",thumbnailUrl=" + thumbnailUrl + ",qrcodeUrl=" + qrcodeUrl + ",isValid=" + isValid + ",createTime=" + createTime + ",modifyTime=" + modifyTime + "->" + super.toString() + "]";
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table three_dimensional
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ThreeDimensional other = (ThreeDimensional) that;
        return (this.getThreeDimensionalId() == null ? other.getThreeDimensionalId() == null : this.getThreeDimensionalId().equals(other.getThreeDimensionalId()))
            && (this.getThreeDimensionalName() == null ? other.getThreeDimensionalName() == null : this.getThreeDimensionalName().equals(other.getThreeDimensionalName()))
            && (this.getArea() == null ? other.getArea() == null : this.getArea().equals(other.getArea()))
            && (this.getResolutionRatio() == null ? other.getResolutionRatio() == null : this.getResolutionRatio().equals(other.getResolutionRatio()))
            && (this.getLatitude() == null ? other.getLatitude() == null : this.getLatitude().equals(other.getLatitude()))
            && (this.getLongitude() == null ? other.getLongitude() == null : this.getLongitude().equals(other.getLongitude()))
            && (this.getDescription() == null ? other.getDescription() == null : this.getDescription().equals(other.getDescription()))
            && (this.getThumbnailUrl() == null ? other.getThumbnailUrl() == null : this.getThumbnailUrl().equals(other.getThumbnailUrl()))
            && (this.getQrcodeUrl() == null ? other.getQrcodeUrl() == null : this.getQrcodeUrl().equals(other.getQrcodeUrl()))
            && (this.getIsValid() == null ? other.getIsValid() == null : this.getIsValid().equals(other.getIsValid()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getModifyTime() == null ? other.getModifyTime() == null : this.getModifyTime().equals(other.getModifyTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table three_dimensional
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getThreeDimensionalId() == null) ? 0 : getThreeDimensionalId().hashCode());
        result = prime * result + ((getThreeDimensionalName() == null) ? 0 : getThreeDimensionalName().hashCode());
        result = prime * result + ((getArea() == null) ? 0 : getArea().hashCode());
        result = prime * result + ((getResolutionRatio() == null) ? 0 : getResolutionRatio().hashCode());
        result = prime * result + ((getLatitude() == null) ? 0 : getLatitude().hashCode());
        result = prime * result + ((getLongitude() == null) ? 0 : getLongitude().hashCode());
        result = prime * result + ((getDescription() == null) ? 0 : getDescription().hashCode());
        result = prime * result + ((getThumbnailUrl() == null) ? 0 : getThumbnailUrl().hashCode());
        result = prime * result + ((getQrcodeUrl() == null) ? 0 : getQrcodeUrl().hashCode());
        result = prime * result + ((getIsValid() == null) ? 0 : getIsValid().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getModifyTime() == null) ? 0 : getModifyTime().hashCode());
        return result;
    }
}