/*
 * Copyright (C) 2015 - 2017 Microscene Inc., All Rights Reserved.
 *
 */
package com.vizen.sd.repository.mysql.domain;

import com.vizen.framework.mybatis.BaseModel;
import java.io.Serializable;
import java.util.Date;

/**
 *
 * @author mark@visualbusiness.com
 * @date 2017-12-20
 *
 */
public class User extends BaseModel implements Serializable {
    private Long userId;

    private String userName;

    /**
     * ����
     */
    private String name;

    /**
     * �ֻ��
     */
    private String phone;

    /**
     * ����
     */
    private String email;

    /**
     * ����
     */
    private String password;

    /**
     * ����ʱ��
     */
    private Date createTime;

    /**
     * �û�״̬Ԥ���ֶ�
     */
    private Byte userStatus;

    /**
     * ����
     */
    private String description;

    /**
     * �û���
     */
    private String userCode;

    /**
     * ����޸�ʱ��
     */
    private Date lastEditTime;

    /**
     * ������
     */
    private Long createUserId;

    /**
     * ����޸���
     */
    private Long lastEditUserId;

    /**
     * ��������id
     */
    private Long departmentId;

    /**
     * �߼�ɾ���ʶ(0��Ч:,1:��Ч)
     */
    private Byte isValid;

    /**
     * Ȩ�޽�ɫid
     */
    private Byte roleId;
    
    private String departmentName;
    
    private String roleName;
    
    private Long roleType;
    
    private PermissionApply apply;
    
    public PermissionApply getApply() {
		return apply;
	}

	public void setApply(PermissionApply apply) {
		this.apply = apply;
	}

	public String getDepartmentName() {
		return departmentName;
	}

	public void setDepartmentName(String departmentName) {
		this.departmentName = departmentName;
	}

	public String getRoleName() {
		return roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	public Long getRoleType() {
		return roleType;
	}

	public void setRoleType(Long roleType) {
		this.roleType = roleType;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     */
    private static final long serialVersionUID = 1L;

    /**
     * @return user_id
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * @param userId
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * @return user_name
     */
    public String getUserName() {
        return userName;
    }

    /**
     * @param userName
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * ��ȡ����
     *
     * @return name - ����
     */
    public String getName() {
        return name;
    }

    /**
     * ��������
     *
     * @param name ����
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * ��ȡ�ֻ��
     *
     * @return phone - �ֻ��
     */
    public String getPhone() {
        return phone;
    }

    /**
     * �����ֻ��
     *
     * @param phone �ֻ��
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * ��ȡ����
     *
     * @return email - ����
     */
    public String getEmail() {
        return email;
    }

    /**
     * ��������
     *
     * @param email ����
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * ��ȡ����
     *
     * @return password - ����
     */
    public String getPassword() {
        return password;
    }

    /**
     * ��������
     *
     * @param password ����
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * ��ȡ����ʱ��
     *
     * @return create_time - ����ʱ��
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * ���ô���ʱ��
     *
     * @param createTime ����ʱ��
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * ��ȡ�û�״̬Ԥ���ֶ�
     *
     * @return user_status - �û�״̬Ԥ���ֶ�
     */
    public Byte getUserStatus() {
        return userStatus;
    }

    /**
     * �����û�״̬Ԥ���ֶ�
     *
     * @param userStatus �û�״̬Ԥ���ֶ�
     */
    public void setUserStatus(Byte userStatus) {
        this.userStatus = userStatus;
    }

    /**
     * ��ȡ����
     *
     * @return description - ����
     */
    public String getDescription() {
        return description;
    }

    /**
     * ��������
     *
     * @param description ����
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * ��ȡ�û���
     *
     * @return user_code - �û���
     */
    public String getUserCode() {
        return userCode;
    }

    /**
     * �����û���
     *
     * @param userCode �û���
     */
    public void setUserCode(String userCode) {
        this.userCode = userCode == null ? null : userCode.trim();
    }

    /**
     * ��ȡ����޸�ʱ��
     *
     * @return last_edit_time - ����޸�ʱ��
     */
    public Date getLastEditTime() {
        return lastEditTime;
    }

    /**
     * ��������޸�ʱ��
     *
     * @param lastEditTime ����޸�ʱ��
     */
    public void setLastEditTime(Date lastEditTime) {
        this.lastEditTime = lastEditTime;
    }

    /**
     * ��ȡ������
     *
     * @return create_user_id - ������
     */
    public Long getCreateUserId() {
        return createUserId;
    }

    /**
     * ���ô�����
     *
     * @param createUserId ������
     */
    public void setCreateUserId(Long createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * ��ȡ����޸���
     *
     * @return last_edit_user_id - ����޸���
     */
    public Long getLastEditUserId() {
        return lastEditUserId;
    }

    /**
     * ��������޸���
     *
     * @param lastEditUserId ����޸���
     */
    public void setLastEditUserId(Long lastEditUserId) {
        this.lastEditUserId = lastEditUserId;
    }

    /**
     * ��ȡ��������id
     *
     * @return department_id - ��������id
     */
    public Long getDepartmentId() {
        return departmentId;
    }

    /**
     * ������������id
     *
     * @param departmentId ��������id
     */
    public void setDepartmentId(Long departmentId) {
        this.departmentId = departmentId;
    }

    /**
     * ��ȡ�߼�ɾ���ʶ(0��Ч:,1:��Ч)
     *
     * @return is_valid - �߼�ɾ���ʶ(0��Ч:,1:��Ч)
     */
    public Byte getIsValid() {
        return isValid;
    }

    /**
     * �����߼�ɾ���ʶ(0��Ч:,1:��Ч)
     *
     * @param isValid �߼�ɾ���ʶ(0��Ч:,1:��Ч)
     */
    public void setIsValid(Byte isValid) {
        this.isValid = isValid;
    }

    /**
     * ��ȡȨ�޽�ɫid
     *
     * @return role_id - Ȩ�޽�ɫid
     */
    public Byte getRoleId() {
        return roleId;
    }

    /**
     * ����Ȩ�޽�ɫid
     *
     * @param roleId Ȩ�޽�ɫid
     */
    public void setRoleId(Byte roleId) {
        this.roleId = roleId;
    }

    @Override
    public String toString() {
        return "User [userId=" + userId + ",userName=" + userName + ",name=" + name + ",phone=" + phone + ",email=" + email + ",password=" + password + ",createTime=" + createTime + ",userStatus=" + userStatus + ",description=" + description + ",userCode=" + userCode + ",lastEditTime=" + lastEditTime + ",createUserId=" + createUserId + ",lastEditUserId=" + lastEditUserId + ",departmentId=" + departmentId + ",isValid=" + isValid + ",roleId=" + roleId + "->" + super.toString() + "]";
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        User other = (User) that;
        return (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getUserName() == null ? other.getUserName() == null : this.getUserName().equals(other.getUserName()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getPhone() == null ? other.getPhone() == null : this.getPhone().equals(other.getPhone()))
            && (this.getEmail() == null ? other.getEmail() == null : this.getEmail().equals(other.getEmail()))
            && (this.getPassword() == null ? other.getPassword() == null : this.getPassword().equals(other.getPassword()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUserStatus() == null ? other.getUserStatus() == null : this.getUserStatus().equals(other.getUserStatus()))
            && (this.getDescription() == null ? other.getDescription() == null : this.getDescription().equals(other.getDescription()))
            && (this.getUserCode() == null ? other.getUserCode() == null : this.getUserCode().equals(other.getUserCode()))
            && (this.getLastEditTime() == null ? other.getLastEditTime() == null : this.getLastEditTime().equals(other.getLastEditTime()))
            && (this.getCreateUserId() == null ? other.getCreateUserId() == null : this.getCreateUserId().equals(other.getCreateUserId()))
            && (this.getLastEditUserId() == null ? other.getLastEditUserId() == null : this.getLastEditUserId().equals(other.getLastEditUserId()))
            && (this.getDepartmentId() == null ? other.getDepartmentId() == null : this.getDepartmentId().equals(other.getDepartmentId()))
            && (this.getIsValid() == null ? other.getIsValid() == null : this.getIsValid().equals(other.getIsValid()))
            && (this.getRoleId() == null ? other.getRoleId() == null : this.getRoleId().equals(other.getRoleId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getUserName() == null) ? 0 : getUserName().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getPhone() == null) ? 0 : getPhone().hashCode());
        result = prime * result + ((getEmail() == null) ? 0 : getEmail().hashCode());
        result = prime * result + ((getPassword() == null) ? 0 : getPassword().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUserStatus() == null) ? 0 : getUserStatus().hashCode());
        result = prime * result + ((getDescription() == null) ? 0 : getDescription().hashCode());
        result = prime * result + ((getUserCode() == null) ? 0 : getUserCode().hashCode());
        result = prime * result + ((getLastEditTime() == null) ? 0 : getLastEditTime().hashCode());
        result = prime * result + ((getCreateUserId() == null) ? 0 : getCreateUserId().hashCode());
        result = prime * result + ((getLastEditUserId() == null) ? 0 : getLastEditUserId().hashCode());
        result = prime * result + ((getDepartmentId() == null) ? 0 : getDepartmentId().hashCode());
        result = prime * result + ((getIsValid() == null) ? 0 : getIsValid().hashCode());
        result = prime * result + ((getRoleId() == null) ? 0 : getRoleId().hashCode());
        return result;
    }
}