/*
 * Copyright (C) 2015 - 2017 Microscene Inc., All Rights Reserved.
 *
 */
package com.vizen.sd.repository.mysql.mapper;

import com.vizen.framework.mybatis.BaseMapper;
import com.vizen.sd.repository.mysql.domain.Department;
import com.vizen.sd.repository.mysql.domain.DepartmentCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface DepartmentMapper extends BaseMapper<Department> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     */
    long countByExample(DepartmentCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     */
    int deleteByExample(DepartmentCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     */
    @Delete({
        "delete from department",
        "where department_id = #{departmentId,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long departmentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     */
    @Insert({
        "insert into department (department_id, department_name, ",
        "description, is_valid, ",
        "create_time, modify_time)",
        "values (#{departmentId,jdbcType=BIGINT}, #{departmentName,jdbcType=VARCHAR}, ",
        "#{description,jdbcType=VARCHAR}, #{isValid,jdbcType=INTEGER}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{modifyTime,jdbcType=TIMESTAMP})"
    })
    int insert(Department record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     */
    int insertSelective(Department record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     */
    List<Department> selectByExample(DepartmentCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     */
    @Select({
        "select",
        "department_id, department_name, description, is_valid, create_time, modify_time",
        "from department",
        "where department_id = #{departmentId,jdbcType=BIGINT}"
    })
    @ResultMap("com.vizen.sd.repository.mysql.mapper.DepartmentMapper.BaseResultMap")
    Department selectByPrimaryKey(Long departmentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     */
    int updateByExampleSelective(@Param("record") Department record, @Param("example") DepartmentCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     */
    int updateByExample(@Param("record") Department record, @Param("example") DepartmentCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     */
    int updateByPrimaryKeySelective(Department record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     */
    @Update({
        "update department",
        "set department_name = #{departmentName,jdbcType=VARCHAR},",
          "description = #{description,jdbcType=VARCHAR},",
          "is_valid = #{isValid,jdbcType=INTEGER},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "modify_time = #{modifyTime,jdbcType=TIMESTAMP}",
        "where department_id = #{departmentId,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(Department record);
}