/*
 * Copyright (C) 2015 - 2017 Microscene Inc., All Rights Reserved.
 *
 */
package com.vizen.sd.repository.mysql.mapper;

import com.vizen.framework.mybatis.BaseMapper;
import com.vizen.sd.repository.mysql.domain.Permission;
import com.vizen.sd.repository.mysql.domain.PermissionCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface PermissionMapper extends BaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     */
    long countByExample(PermissionCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     */
    int deleteByExample(PermissionCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     */
    @Delete({
        "delete from permission",
        "where permission_id = #{permissionId,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long permissionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     */
    @Insert({
        "insert into permission (permission_id, resource_id, ",
        "menu_id, role_id, is_valid, ",
        "create_time)",
        "values (#{permissionId,jdbcType=BIGINT}, #{resourceId,jdbcType=BIGINT}, ",
        "#{menuId,jdbcType=BIGINT}, #{roleId,jdbcType=BIGINT}, #{isValid,jdbcType=INTEGER}, ",
        "#{createTime,jdbcType=TIMESTAMP})"
    })
    int insert(Permission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     */
    int insertSelective(Permission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     */
    List<Permission> selectByExample(PermissionCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     */
    @Select({
        "select",
        "permission_id, resource_id, menu_id, role_id, is_valid, create_time",
        "from permission",
        "where permission_id = #{permissionId,jdbcType=BIGINT}"
    })
    @ResultMap("com.vizen.sd.repository.mysql.mapper.PermissionMapper.BaseResultMap")
    Permission selectByPrimaryKey(Long permissionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     */
    int updateByExampleSelective(@Param("record") Permission record, @Param("example") PermissionCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     */
    int updateByExample(@Param("record") Permission record, @Param("example") PermissionCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     */
    int updateByPrimaryKeySelective(Permission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     */
    @Update({
        "update permission",
        "set resource_id = #{resourceId,jdbcType=BIGINT},",
          "menu_id = #{menuId,jdbcType=BIGINT},",
          "role_id = #{roleId,jdbcType=BIGINT},",
          "is_valid = #{isValid,jdbcType=INTEGER},",
          "create_time = #{createTime,jdbcType=TIMESTAMP}",
        "where permission_id = #{permissionId,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(Permission record);
}