/*
 * Copyright (C) 2015 - 2017 Microscene Inc., All Rights Reserved.
 *
 */
package com.vizen.sd.repository.mysql.mapper;

import com.vizen.framework.mybatis.BaseMapper;
import com.vizen.sd.repository.mysql.domain.Poi;
import com.vizen.sd.repository.mysql.domain.PoiCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface PoiMapper extends BaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poi
     */
    long countByExample(PoiCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poi
     */
    int deleteByExample(PoiCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poi
     */
    @Delete({
        "delete from poi",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poi
     */
    @Insert({
        "insert into poi (id, name, ",
        "desc, province_id, ",
        "city_id, county_id, ",
        "area_id, coordsys, ",
        "lnglat, lat, lng, ",
        "direction, height, ",
        "camera_type, photo_time, ",
        "thumbnail, creator_id, ",
        "create_time, updater_id, ",
        "update_yime, tag, ",
        "pano_id, file_name, ",
        "is_finish, is_valid)",
        "values (#{id,jdbcType=VARCHAR}, #{name,jdbcType=VARCHAR}, ",
        "#{desc,jdbcType=VARCHAR}, #{provinceId,jdbcType=VARCHAR}, ",
        "#{cityId,jdbcType=VARCHAR}, #{countyId,jdbcType=VARCHAR}, ",
        "#{areaId,jdbcType=VARCHAR}, #{coordsys,jdbcType=INTEGER}, ",
        "#{lnglat,jdbcType=VARCHAR}, #{lat,jdbcType=DECIMAL}, #{lng,jdbcType=DECIMAL}, ",
        "#{direction,jdbcType=VARCHAR}, #{height,jdbcType=INTEGER}, ",
        "#{cameraType,jdbcType=INTEGER}, #{photoTime,jdbcType=TIMESTAMP}, ",
        "#{thumbnail,jdbcType=VARCHAR}, #{creatorId,jdbcType=VARCHAR}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{updaterId,jdbcType=VARCHAR}, ",
        "#{updateYime,jdbcType=TIMESTAMP}, #{tag,jdbcType=VARCHAR}, ",
        "#{panoId,jdbcType=VARCHAR}, #{fileName,jdbcType=VARCHAR}, ",
        "#{isFinish,jdbcType=INTEGER}, #{isValid,jdbcType=INTEGER})"
    })
    int insert(Poi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poi
     */
    int insertSelective(Poi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poi
     */
    List<Poi> selectByExample(PoiCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poi
     */
    @Select({
        "select",
        "id, name, desc, province_id, city_id, county_id, area_id, coordsys, lnglat, ",
        "lat, lng, direction, height, camera_type, photo_time, thumbnail, creator_id, ",
        "create_time, updater_id, update_yime, tag, pano_id, file_name, is_finish, is_valid",
        "from poi",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    @ResultMap("com.vizen.sd.repository.mysql.mapper.PoiMapper.BaseResultMap")
    Poi selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poi
     */
    int updateByExampleSelective(@Param("record") Poi record, @Param("example") PoiCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poi
     */
    int updateByExample(@Param("record") Poi record, @Param("example") PoiCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poi
     */
    int updateByPrimaryKeySelective(Poi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poi
     */
    @Update({
        "update poi",
        "set name = #{name,jdbcType=VARCHAR},",
          "desc = #{desc,jdbcType=VARCHAR},",
          "province_id = #{provinceId,jdbcType=VARCHAR},",
          "city_id = #{cityId,jdbcType=VARCHAR},",
          "county_id = #{countyId,jdbcType=VARCHAR},",
          "area_id = #{areaId,jdbcType=VARCHAR},",
          "coordsys = #{coordsys,jdbcType=INTEGER},",
          "lnglat = #{lnglat,jdbcType=VARCHAR},",
          "lat = #{lat,jdbcType=DECIMAL},",
          "lng = #{lng,jdbcType=DECIMAL},",
          "direction = #{direction,jdbcType=VARCHAR},",
          "height = #{height,jdbcType=INTEGER},",
          "camera_type = #{cameraType,jdbcType=INTEGER},",
          "photo_time = #{photoTime,jdbcType=TIMESTAMP},",
          "thumbnail = #{thumbnail,jdbcType=VARCHAR},",
          "creator_id = #{creatorId,jdbcType=VARCHAR},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "updater_id = #{updaterId,jdbcType=VARCHAR},",
          "update_yime = #{updateYime,jdbcType=TIMESTAMP},",
          "tag = #{tag,jdbcType=VARCHAR},",
          "pano_id = #{panoId,jdbcType=VARCHAR},",
          "file_name = #{fileName,jdbcType=VARCHAR},",
          "is_finish = #{isFinish,jdbcType=INTEGER},",
          "is_valid = #{isValid,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(Poi record);
}