/*
 * Copyright (C) 2015 - 2017 Microscene Inc., All Rights Reserved.
 *
 */
package com.vizen.sd.repository.mysql.mapper;

import com.vizen.framework.mybatis.BaseMapper;
import com.vizen.sd.repository.mysql.domain.ThreeDimensional;
import com.vizen.sd.repository.mysql.domain.ThreeDimensionalCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface ThreeDimensionalMapper extends BaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table three_dimensional
     */
    long countByExample(ThreeDimensionalCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table three_dimensional
     */
    int deleteByExample(ThreeDimensionalCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table three_dimensional
     */
    @Delete({
        "delete from three_dimensional",
        "where three_dimensional_id = #{threeDimensionalId,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String threeDimensionalId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table three_dimensional
     */
    @Insert({
        "insert into three_dimensional (three_dimensional_id, three_dimensional_name, ",
        "area, resolution_ratio, ",
        "latitude, longitude, ",
        "description, thumbnail_url, ",
        "qrcode_url, is_valid, ",
        "create_time, modify_time)",
        "values (#{threeDimensionalId,jdbcType=VARCHAR}, #{threeDimensionalName,jdbcType=VARCHAR}, ",
        "#{area,jdbcType=DECIMAL}, #{resolutionRatio,jdbcType=BIGINT}, ",
        "#{latitude,jdbcType=VARCHAR}, #{longitude,jdbcType=VARCHAR}, ",
        "#{description,jdbcType=VARCHAR}, #{thumbnailUrl,jdbcType=VARCHAR}, ",
        "#{qrcodeUrl,jdbcType=VARCHAR}, #{isValid,jdbcType=TINYINT}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{modifyTime,jdbcType=TIMESTAMP})"
    })
    int insert(ThreeDimensional record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table three_dimensional
     */
    int insertSelective(ThreeDimensional record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table three_dimensional
     */
    List<ThreeDimensional> selectByExample(ThreeDimensionalCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table three_dimensional
     */
    @Select({
        "select",
        "three_dimensional_id, three_dimensional_name, area, resolution_ratio, latitude, ",
        "longitude, description, thumbnail_url, qrcode_url, is_valid, create_time, modify_time",
        "from three_dimensional",
        "where three_dimensional_id = #{threeDimensionalId,jdbcType=VARCHAR}"
    })
    @ResultMap("com.vizen.sd.repository.mysql.mapper.ThreeDimensionalMapper.BaseResultMap")
    ThreeDimensional selectByPrimaryKey(String threeDimensionalId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table three_dimensional
     */
    int updateByExampleSelective(@Param("record") ThreeDimensional record, @Param("example") ThreeDimensionalCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table three_dimensional
     */
    int updateByExample(@Param("record") ThreeDimensional record, @Param("example") ThreeDimensionalCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table three_dimensional
     */
    int updateByPrimaryKeySelective(ThreeDimensional record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table three_dimensional
     */
    @Update({
        "update three_dimensional",
        "set three_dimensional_name = #{threeDimensionalName,jdbcType=VARCHAR},",
          "area = #{area,jdbcType=DECIMAL},",
          "resolution_ratio = #{resolutionRatio,jdbcType=BIGINT},",
          "latitude = #{latitude,jdbcType=VARCHAR},",
          "longitude = #{longitude,jdbcType=VARCHAR},",
          "description = #{description,jdbcType=VARCHAR},",
          "thumbnail_url = #{thumbnailUrl,jdbcType=VARCHAR},",
          "qrcode_url = #{qrcodeUrl,jdbcType=VARCHAR},",
          "is_valid = #{isValid,jdbcType=TINYINT},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "modify_time = #{modifyTime,jdbcType=TIMESTAMP}",
        "where three_dimensional_id = #{threeDimensionalId,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(ThreeDimensional record);
}