export const STORE_READY = 'STORE_READY';
export const SET_API_TOKEN = 'SET_API_TOKEN';

export const USER_NEED_RELOGIN = 'USER_NEED_RELOGIN';
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE';

// orders
export const ORDER_GET_REQUEST = 'ORDER_GET_REQUEST';
export const ORDER_GET_SUCCESS = 'ORDER_GET_SUCCESS';
export const ORDER_GET_FAILURE = 'ORDER_GET_FAILURE';
export const ORDER_CANCEL_REQUEST = 'ORDER_CANCEL_REQUEST';
export const ORDER_CANCEL_SUCCESS = 'ORDER_CANCEL_SUCCESS';
export const ORDER_CANCEL_FAILURE = 'ORDER_CANCEL_FAILURE';
export const ORDER_SIGN_REQUEST = 'ORDER_SIGN_REQUEST';
export const ORDER_SIGN_SUCCESS = 'ORDER_SIGN_SUCCESS';
export const ORDER_SIGN_FAILURE = 'ORDER_SIGN_FAILURE';
export const ORDER_DELETE_REQUEST = 'ORDER_DELETE_REQUEST';
export const ORDER_DELETE_SUCCESS = 'ORDER_DELETE_SUCCESS';
export const ORDER_DELETE_FAILURE = 'ORDER_DELETE_FAILURE';
export const ORDER_DETAIL_REQUEST = 'ORDER_DETAIL_REQUEST';
export const ORDER_DETAIL_SUCCESS = 'ORDER_DETAIL_SUCCESS';
export const ORDER_DETAIL_FAILURE = 'ORDER_DETAIL_FAILURE';
export const ORDER_TYPE_CHANGE_REQUEST = 'ORDER_TYPE_CHANGE_REQUEST';
export const ORDER_TYPE_CHANGE_SUCCESS = 'ORDER_TYPE_CHANGE_SUCCESS';
export const ORDER_TYPE_CHANGE_FAILURE = 'ORDER_TYPE_CHANGE_FAILURE';
export const ORDER_NEXTPAGE_REQUEST = 'ORDER_NEXTPAGE_REQUEST';
export const ORDER_NEXTPAGE_SUCCESS = 'ORDER_NEXTPAGE_SUCCESS';
export const ORDER_NEXTPAGE_FAILURE = 'ORDER_NEXTPAGE_FAILURE';
export const ORDER_DETAIL_PAY_REQUEST = 'ORDER_DETAIL_PAY_REQUEST';
export const ORDER_DETAIL_PAY_SUCCESS = 'ORDER_DETAIL_PAY_SUCCESS';
export const ORDER_DETAIL_PAY_FAILURE = 'ORDER_DETAIL_PAY_FAILURE';
export const ORDER_DETAIL_CANCEL_REQUEST = 'ORDER_DETAIL_CANCEL_REQUEST';
export const ORDER_DETAIL_CANCEL_SUCCESS = 'ORDER_DETAIL_CANCEL_SUCCESS';
export const ORDER_DETAIL_CANCEL_FAILURE = 'ORDER_DETAIL_CANCEL_FAILURE';
export const ORDER_DETAIL_SIGN_REQUEST = 'ORDER_DETAIL_SIGN_REQUEST';
export const ORDER_DETAIL_SIGN_SUCCESS = 'ORDER_DETAIL_SIGN_SUCCESS';
export const ORDER_DETAIL_SIGN_FAILURE = 'ORDER_DETAIL_SIGN_FAILURE';
export const ORDER_ADDRESS_UPDATE_REQUEST = 'ORDER_ADDRESS_UPDATE_REQUEST';
export const ORDER_ADDRESS_UPDATE_SUCCESS = 'ORDER_ADDRESS_UPDATE_SUCCESS';
export const ORDER_ADDRESS_UPDATE_FAILURE = 'ORDER_ADDRESS_UPDATE_FAILURE';

export const PRODUCT_DETAIL_REQUEST = 'PRODUCT_DETAIL_REQUEST';
export const PRODUCT_DETAIL_SUCCESS = 'PRODUCT_DETAIL_SUCCESS';
export const PRODUCT_DETAIL_FAILURE = 'PRODUCT_DETAIL_FAILURE';

export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAILURE = 'PRODUCT_LIST_FAILURE';

// address
export const ADDRESS_DETAIL_REQUEST = 'ADDRESS_DETAIL_REQUEST';
export const ADDRESS_DETAIL_SUCCESS = 'ADDRESS_DETAIL_SUCCESS';
export const ADDRESS_DETAIL_FAILURE = 'ADDRESS_DETAIL_FAILURE';
export const ADDRESS_DETAIL_INIT_REQUEST    = 'ADDRESS_DETAIL_INIT_REQUEST';
export const ADDRESS_DETAIL_INIT_SUCCESS    = 'ADDRESS_DETAIL_INIT_SUCCESS';

export const ADDRESS_LIST_REQUEST = 'ADDRESS_LIST_REQUEST';
export const ADDRESS_LIST_SUCCESS = 'ADDRESS_LIST_SUCCESS';
export const ADDRESS_LIST_FAILURE = 'ADDRESS_LIST_FAILURE';

export const ADDRESS_SAVE_REQUEST = 'ADDRESS_SAVE_REQUEST';
export const ADDRESS_SAVE_SUCCESS = 'ADDRESS_SAVE_SUCCESS';
export const ADDRESS_SAVE_FAILURE = 'ADDRESS_SAVE_FAILURE';
export const ADDRESS_DATA_MODIFY = 'ADDRESS_DATA_MODIFY';
export const ADDRESS_DATA_VALID = 'ADDRESS_DATA_VALID';
export const ADDRESS_DATA_INVALID = 'ADDRESS_DATA_INVALID';

export const ADDRESS_REMOVE_REQUEST = 'ADDRESS_REMOVE_REQUEST';
export const ADDRESS_REMOVE_SUCCESS = 'ADDRESS_REMOVE_SUCCESS';
export const ADDRESS_REMOVE_FAILURE = 'ADDRESS_REMOVE_FAILURE';

export const REGION_LIST_REQUEST = 'REGION_LIST_REQUEST';
export const REGION_LIST0_SUCCESS = 'REGION_LIST0_SUCCESS';
export const REGION_LIST_FAILURE = 'REGION_LIST_FAILURE';
export const REGION_EIDT_REQUEST = 'REGION_EIDT_REQUEST';
export const REGION_EIDT_SUCCESS = 'REGION_EIDT_SUCCESS';
export const REGION_EIDT_FAILURE = 'REGION_EIDT_FAILURE';

export const REGION_LIST1_SUCCESS = 'REGION_LIST1_SUCCESS';
export const REGION_LIST2_SUCCESS = 'REGION_LIST2_SUCCESS';
export const REGION_LIST_INIT = 'REGION_LIST_INIT';

export const UPDATE_VIEW_CONFIG = 'UPDATE_VIEW_CONFIG';

export const ORDER_PRE_DETAIL_INIT_START = 'ORDER_PRE_DETAIL_INIT_START';
export const ORDER_PRE_DETAIL_INIT_END = 'ORDER_PRE_DETAIL_INIT_END';
export const ORDER_PRE_DETAIL_REQUEST = 'ORDER_PRE_DETAIL_REQUEST';
export const ORDER_PRE_DETAIL_SUCCESS = 'ORDER_PRE_DETAIL_SUCCESS';
export const ORDER_PRE_DETAIL_FAILURE = 'ORDER_PRE_DETAIL_FAILURE';

export const ORDER_SUBMIT_REQUEST = 'ORDER_SUBMIT_REQUEST';
export const ORDER_SUBMIT_SUCCESS = 'ORDER_SUBMIT_SUCCESS';
export const ORDER_SUBMIT_FAILURE = 'ORDER_SUBMIT_FAILURE';

export const AUTH_ACTION_DISPATCH = 'AUTH_ACTION_DISPATCH';

export const PAY_REQUEST = 'PAY_REQUEST';
export const PAY_SUCCESS = 'PAY_SUCCESS';
export const PAY_CANCEL = 'PAY_CANCEL';
export const PAY_FAILURE = 'PAY_FAILURE';

export const SWITCH_TAB_SUCCESS = 'SWITCH_TAB_SUCCESS';


/* 售后 */
export const REFUND_CHANGE_START = 'REFUND_CHANGE_START';
export const REFUND_CHANGE_END = 'REFUND_CHANGE_END';
export const REFUND_SUBMIT_REQUEST = 'REFUND_SUBMIT_REQUEST';
export const REFUND_SUBMIT_SUCCESS = 'REFUND_SUBMIT_SUCCESS';
export const REFUND_SUBMIT_FAILURE = 'REFUND_SUBMIT_FAILURE';
export const REFUND_DETAIL_REQUEST = 'REFUND_DETAIL_REQUEST';
export const REFUND_DETAIL_SUCCESS = 'REFUND_DETAIL_SUCCESS';
export const REFUND_DETAIL_FAILURE = 'REFUND_DETAIL_FAILURE';
export const REFUND_CANCEL_REQUEST = 'REFUND_CANCEL_REQUEST';
export const REFUND_CANCEL_SUCCESS = 'REFUND_CANCEL_SUCCESS';
export const REFUND_CANCEL_FAILURE = 'REFUND_CANCEL_FAILURE';
export const QUNID_REQUEST = 'QUNID_REQUEST';
export const QUNID_SUCCESS = 'QUNID_SUCCESS';
export const QUNID_FAILURE = 'QUNID_FAILURE';

/* 中间页 */
export const MIDDLE_PRODUCT_REQUEST = 'MIDDLE_PRODUCT_REQUEST';
export const MIDDLE_PRODUCT_SUCCESS = 'MIDDLE_PRODUCT_SUCCESS';
export const MIDDLE_PRODUCT_FAILURE = 'MIDDLE_PRODUCT_FAILURE';

export const MIDDLE_OLD_PRODUCTS_REQUEST = 'MIDDLE_OLD_PRODUCTS_REQUEST';
export const MIDDLE_OLD_PRODUCTS_SUCCESS = 'MIDDLE_OLD_PRODUCTS_SUCCESS';
export const MIDDLE_OLD_PRODUCTS_FAILURE = 'MIDDLE_OLD_PRODUCTS_FAILURE';
export const MIDDLE_OLD_PRODUCTS_SHOW = 'MIDDLE_OLD_PRODUCTS_SHOW';

export const MIDDLE_NEW_PRODUCT_REQUEST = 'MIDDLE_NEW_PRODUCT_REQUEST';
export const MIDDLE_NEW_PRODUCT_SUCCESS = 'MIDDLE_NEW_PRODUCT_SUCCESS';
export const MIDDLE_NEW_PRODUCT_FAILURE = 'MIDDLE_NEW_PRODUCT_FAILURE';

export const MIDDLE_PRODUCTS_LIST_REQUEST = 'MIDDLE_PRODUCTS_LIST_REQUEST';
export const MIDDLE_PRODUCTS_LIST_SUCCESS = 'MIDDLE_PRODUCTS_LIST_SUCCESS';
export const MIDDLE_PRODUCTS_LIST_FAILURE = 'MIDDLE_PRODUCTS_LIST_FAILURE';

export const MIDDLE_PRODUCTS_LIST_INIT_REQUEST = 'MIDDLE_PRODUCTS_LIST_INIT_REQUEST';
export const MIDDLE_PRODUCTS_LIST_INIT_SUCCESS = 'MIDDLE_PRODUCTS_LIST_INIT_SUCCESS';
export const MIDDLE_PRODUCTS_LIST_INIT_FAILURE = 'MIDDLE_PRODUCTS_LIST_INIT_FAILURE';

/* 拼团相关 */
export const GROUPS_DETAIL_REQUEST = 'GROUPS_DETAIL_REQUEST';
export const GROUPS_DETAIL_SUCCESS = 'GROUPS_DETAIL_SUCCESS';
export const GROUPS_DETAIL_FAILURE = 'GROUPS_DETAIL_FAILURE';

export const PRODUCT_TUAN_LIST_REQUEST = 'PRODUCT_TUAN_LIST_REQUEST';
export const PRODUCT_TUAN_LIST_SUCCESS = 'PRODUCT_TUAN_LIST_SUCCESS';
export const PRODUCT_TUAN_LIST_FAILURE = 'PRODUCT_TUAN_LIST_FAILURE';

export const ORDER_GROUP_GET_REQUEST = 'ORDER_GROUP_GET_REQUEST';
export const ORDER_GROUP_GET_SUCCESS = 'ORDER_GROUP_GET_SUCCESS';
export const ORDER_GROUP_GET_FAILURE = 'ORDER_GROUP_GET_FAILURE';

export const ORDER_GROUP_TYPE_CHANGE_REQUEST = 'ORDER_GROUP_TYPE_CHANGE_REQUEST';
export const ORDER_GROUP_TYPE_CHANGE_SUCCESS = 'ORDER_GROUP_TYPE_CHANGE_SUCCESS';
export const ORDER_GROUP_TYPE_CHANGE_FAILURE = 'ORDER_GROUP_TYPE_CHANGE_FAILURE';

/* 优惠券相关 */
export const COUPONS_LIST_GET_REQUEST = 'COUPONS_LIST_GET_REQUEST';
export const COUPONS_LIST_GET_SUCCESS = 'COUPONS_LIST_GET_SUCCESS';
export const COUPONS_LIST_GET_FAILURE = 'COUPONS_LIST_GET_FAILURE';

export const COUPONS_ORDERS_GET_REQUEST = 'COUPONS_ORDERS_GET_REQUEST';
export const COUPONS_ORDERS_GET_SUCCESS = 'COUPONS_ORDERS_GET_SUCCESS';
export const COUPONS_ORDERS_GET_FAILURE = 'COUPONS_ORDERS_GET_FAILURE';

export const COUPONS_SELECTED_CHANGE_REQUEST = 'COUPONS_SELECTED_CHANGE_REQUEST';
export const COUPONS_SELECTED_CHANGE_SUCCESS = 'COUPONS_SELECTED_CHANGE_SUCCESS';
export const COUPONS_SELECTED_CHANGE_FAILURE = 'COUPONS_SELECTED_CHANGE_FAILURE';

export const COUPONS_LIST_TYPE_CHANGE_REQUEST = 'COUPONS_LIST_TYPE_CHANGE_REQUEST';

export const COUPONS_LIST_REQUEST = 'COUPONS_LIST_REQUEST';
export const COUPONS_LIST_SUCCESS = 'COUPONS_LIST_SUCCESS';
export const COUPONS_LIST_FAILURE = 'COUPONS_LIST_FAILURE';

export const COUPONS_DRAW_REQUEST = 'COUPONS_DRAW_REQUEST';
export const COUPONS_DRAW_SUCCESS = 'COUPONS_DRAW_SUCCESS';
export const COUPONS_DRAW_FAILURE = 'COUPONS_DRAW_FAILURE';

export const MODAL_COUPONS_SHOW = 'MODAL_COUPONS_SHOW';
export const MODAL_COUPONS_HIDE = 'MODAL_COUPONS_HIDE';

export const DATA_REDUCER_CLEAR = 'DATA_REDUCER_CLEAR';

export const FORM_ID_SAVE_REQUEST = 'FORM_ID_SAVE_REQUEST';

